#!/usr/bin/env python3
"""M6-T2 — validate the torchship glTF export in Blender (real importer).

BUILD_PLAN M6-T2: "Validate export in Blender (materials intact, deck groups
present, no flipped normals)". This script runs Blender *headless* (background)
via the `bpy` Python module, imports each written `.gltf` with Blender's own
glTF importer (`bpy.ops.import_scene.gltf`), and reports the three acceptance
criteria as JSON:

  * deckGroups — the scene roots are the deck groups `deck-0…deck-N`, in order,
    each importing with geometry under it (checked both in the file's scene
    order and in Blender's object tree);
  * materials  — every material name the file declares survives the import
    (Blender's material list == the file's), and every mesh actually uses them;
  * normals    — no polygon winds against its own corner (split) normals. A
    flipped face is one Blender's `recalculate normals outside` would have to
    fix; a correct export has ZERO.

Run it with a Python that has `bpy` available — either Blender's bundled python
or a pip install of the `bpy` wheel:

    pip install bpy           # Blender as a Python module (needs a matching CPython)
    python scripts/blender-validate.py dist/export/*.gltf

The `.gltf` corpus is (re)generated by the vitest suite:

    npx vitest run src/export/blender

Exit code: 0 if every file is clean, 1 if any file has a problem, 2 on usage,
3 if bpy is not importable. Prints the report as JSON on stdout.
"""

from __future__ import annotations

import contextlib
import ctypes
import json
import logging
import os
import re
import sys

DECK_RE = re.compile(r"^deck-\d+$")
# Flipped-normal tolerance: allow float noise, judge a real inversion.
FLIP_DOT_EPS = -1e-4


@contextlib.contextmanager
def _quiet_stdout():
    """Send stdout (Python's and C stdio's fd 1) to /dev/null for the duration.

    Blender's report system writes an import error to the C-level stdout, which
    is full-buffered when it is not a TTY; that buffer would otherwise flush to
    the *restored* fd 1 at exit and corrupt our JSON. So we flush both layers
    while fd 1 still points at /dev/null, then restore."""
    with open(os.devnull, "w") as devnull:
        sys.stdout.flush()
        saved = os.dup(1)
        os.dup2(devnull.fileno(), 1)
        try:
            yield
        finally:
            try:
                sys.stdout.flush()
                ctypes.CDLL(None).fflush(None)
            except Exception:  # pragma: no cover — best-effort silencing
                pass
            os.dup2(saved, 1)
            os.close(saved)


def _read_document(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _expected_deck_names(doc: dict) -> list[str]:
    nodes = doc.get("nodes", [])
    scenes = doc.get("scenes", [])
    scene = scenes[doc.get("scene", 0)] if scenes else {}
    return [nodes[i].get("name") for i in scene.get("nodes", [])]


def validate(path: str) -> dict:
    """Import one .gltf with Blender and return the acceptance report."""
    import bpy  # noqa: PLC0415 — Blender is only available at run time

    problems: list[str] = []
    bpy.ops.wm.read_factory_settings(use_empty=True)
    try:
        with _quiet_stdout():
            bpy.ops.import_scene.gltf(filepath=path)
    except Exception as error:  # noqa: BLE001 — report any import failure as data
        return {
            "file": path,
            "deckGroups": {"expected": [], "found": []},
            "materials": {"file": [], "blender": [], "used": []},
            "normals": {"meshes": 0, "polygons": 0, "flipped": 0},
            "problems": [f"import: Blender refused the file ({error})"],
            "ok": False,
        }

    doc = _read_document(path)

    # 1. Deck groups present, in order, each carrying geometry.
    expected = _expected_deck_names(doc)
    roots = [obj.name for obj in bpy.data.objects if obj.parent is None]
    found = [name for name in roots if DECK_RE.match(name)]
    if found != expected:
        problems.append(
            f"deck groups: Blender imported roots {found} — file scene order is {expected}"
        )
    for name in expected:
        obj = bpy.data.objects.get(name)
        if obj is None:
            problems.append(f"deck groups: '{name}' did not import")
        elif len(obj.children) == 0:
            problems.append(f"deck groups: '{name}' imported with nothing under it")

    # 2. Materials intact: the file's materials all resolve, and are all used.
    file_materials = [material.get("name") for material in doc.get("materials", [])]
    blender_materials = sorted(material.name for material in bpy.data.materials)
    used: set[str] = set()
    for mesh in bpy.data.meshes:
        for material in mesh.materials:
            if material is not None:
                used.add(material.name)
    missing = sorted(set(file_materials) - set(blender_materials))
    if missing:
        problems.append(f"materials: lost on import: {missing}")
    unused = sorted(set(file_materials) - used)
    if unused:
        problems.append(f"materials: imported but unused by any mesh: {unused}")
    if len(blender_materials) != len(file_materials):
        problems.append(
            f"materials: Blender has {len(blender_materials)} — file declares {len(file_materials)}"
        )

    # 3. No flipped normals: every polygon winds with its corner normals.
    polygons = 0
    flipped = 0
    for mesh in bpy.data.meshes:
        for poly in mesh.polygons:
            polygons += 1
            start = poly.loop_start
            ax = ay = az = 0.0
            for offset in range(poly.loop_total):
                vector = mesh.corner_normals[start + offset].vector
                ax += vector[0]
                ay += vector[1]
                az += vector[2]
            length = (ax * ax + ay * ay + az * az) ** 0.5
            if length < 1e-9:
                continue  # opposing corner normals: no orientation to judge
            normal = poly.normal
            dot = (normal[0] * ax + normal[1] * ay + normal[2] * az) / length
            if dot < FLIP_DOT_EPS:
                flipped += 1
    if flipped:
        problems.append(
            f"normals: {flipped} polygon(s) wind against their corner normals — flipped normals"
        )

    return {
        "file": path,
        "deckGroups": {"expected": expected, "found": found},
        "materials": {
            "file": file_materials,
            "blender": blender_materials,
            "used": sorted(used),
        },
        "normals": {
            "meshes": len(bpy.data.meshes),
            "polygons": polygons,
            "flipped": flipped,
        },
        "problems": problems,
        "ok": not problems,
    }


def main(argv: list[str]) -> int:
    paths = [arg for arg in argv[1:] if not arg.startswith("-")]
    if not paths:
        print("usage: blender-validate.py <file.gltf> [...]", file=sys.stderr)
        return 2
    try:
        import bpy  # noqa: PLC0415
    except ImportError:
        print(
            json.dumps(
                {
                    "error": "Blender (bpy) is not importable. Install it "
                    "(`pip install bpy`) or run this with Blender's own python.",
                }
            )
        )
        return 3
    # Silence Blender's importer logging so stdout is pure JSON.
    logging.disable(logging.CRITICAL)
    reports = [validate(path) for path in paths]
    ok = all(report["ok"] for report in reports)
    print(
        json.dumps(
            {"blender": bpy.app.version_string, "files": reports, "ok": ok},
            indent=2,
        )
    )
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
