/**
 * M2-T5 — the authored ENGINEERING module: the reactor room.
 *
 * PRD §4 landmark: "The reactor room: the drive's glow visible through a
 * shielded window / grating, radiation trefoil, warning striping." The room is
 * one deck module on the M1-T2 authoring frame — floor at local y = 0,
 * footprint centred on the origin in XZ, the standardized `spine-door` flush in
 * the module's −z face at the standard 1.0 m centre (src/fixtures/layout.ts:
 * every room attaches to the spine's +z face, so the −z face is the centreline
 * breach to the shaft). Engineering is the AFT-most room of the ship (the
 * fixtures put it one deck above the drive), so it is the room the drive's
 * heat actually reaches.
 *
 * Reading the room from the spine door (aft, −z) toward the bow (+z):
 *  - the MACHINERY BAY fills the aft two-thirds: a stores locker bank on the
 *    port wall, a machinery locker and the console bench along the starboard
 *    wall, and a spares locker forward of the stores on the port side — the
 *    working half of the room, laid out around a clear centreline lane from
 *    the spine door to the reactor bulkhead;
 *  - the REACTOR BULKHEAD walls off the bow end: a full-width partition across
 *    the room at z = 1.4 with a 0.8 × 1.6 m access doorway whose bottom edge is
 *    on the deck (you walk in through it), sealed by its own socket-centred
 *    hatch;
 *  - the DRIVE GLOW WINDOW (the §4 landmark) is set into that bulkhead's room
 *    face: a shielded window with grating bars over the drive's glow, so the
 *    light in the room comes through a shield, not from a screen;
 *  - the RADIATION PLACARD hangs beside the access door, its three-fold mark
 *    proud of its plate;
 *  - CERAMIC HEAT SHIELDS with their own worn hazard stripes clad the bulkhead
 *    either side of the window — the §4 "ceramic heat shielding near the
 *    drive" and "warning striping" in one kit piece;
 *  - everything else is the room's practical lighting (three ceiling panels, a
 *    wall-recessed task strip over the bench, the console display) and exposed
 *    conduit routing.
 *
 * The starboard wall carries the contract's `high-hatch` socket (M1-T3
 * contractKit): the kit's ONE deliberate non-standard door — 0.8 × 1.6 m with
 * its centre at 1.2 m, i.e. +0.2 m of declared deck offset (the M0-T2 spike's
 * pathological-join author and the validator's deck-offset case). The wall
 * panel is cut with the bulkhead builder's `door.centerX`/`door.centerY`
 * (never freehand geometry, BUILD_PLAN rule 8) and the opening is sealed with a
 * socket-centred hatch, exactly the way the spine door is. Both hatches belong
 * to the room; the M2-T6 spine module supplies the shaft + per-deck sockets and
 * adds NO hatch of its own.
 *
 * Everything is generated by the M2-T1 builders and placed through `placePart`
 * / `placePoint`; `ENGINEERING_ASSEMBLIES` is the authored truth, and the
 * anchors (light sockets, equipment slots) are DERIVED from those placements so
 * they can never drift from the geometry. The manifest's collision hint is
 * derived the same way (`collisionBoxesFor`).
 */

import { DECK_CLEAR_M, STANDARD_DOOR_CENTER_M } from '../../types'
import type { EquipmentSlot, LightKind, LightSocket, Vec3 } from '../../types'
import {
  bulkheadParts,
  conduitRunParts,
  deckPlateParts,
  glowWindowParts,
  hatchParts,
  heatShieldParts,
  lockerParts,
  panelLightParts,
  radiationSignParts,
  screenParts,
  tableParts,
} from '../parts'
import { placePoint } from './placement'
import { collisionBoxesFor } from './types'
import type { AuthoredModule, ModuleAssembly } from './types'

/* ----------------------------------------------------------------- geometry */

/** Engineering-module box [width, height, depth] m — the M0-T5 contract footprint. */
const WIDTH = 4.5
const DEPTH = 4.8
const HEIGHT = DECK_CLEAR_M
const HALF_X = WIDTH / 2
const HALF_Z = DEPTH / 2

/** Bulkhead thickness (kit default), m. */
const WALL_T = 0.1
/** Wall centre planes (flush with the module faces) and the room's inner faces. */
const WALL_CENTER_X = HALF_X - WALL_T / 2
const INNER_X = HALF_X - WALL_T

/** Rotation that reads "along the room": yaw 1 runs the panel's local +X along module −Z. */
const PORT_WALL_ROTATION = 1 as const
/** Yaw 3 runs the panel's local +X along module +Z — how the starboard wall is authored. */
const STBD_WALL_ROTATION = 3 as const

/* --------------------------------------------------------------- the socket */

/** The contract's non-standard door: +x (starboard) face, 0.6 m bow-ward. */
const HIGH_HATCH_Z = 0.6
/** …carrying the contract's 0.8 × 1.6 m opening… */
const HIGH_HATCH_WIDTH = 0.8
const HIGH_HATCH_HEIGHT = 1.6
/** …whose centre sits 0.2 m above the standard 1.0 m door centre (deck offset). */
const HIGH_HATCH_CENTER_Y = STANDARD_DOOR_CENTER_M + 0.2

/* --------------------------------------------------------------- reactor bay */

/**
 * The reactor bulkhead: a full-width partition across the room, closing off the
 * bow compartment the drive's heat comes through.
 */
const REACTOR_PARTITION_Z = 1.4
/** Its room-side (aft) face — where the window, placard and shields mount. */
const REACTOR_FACE_Z = REACTOR_PARTITION_Z - WALL_T / 2
/** The 0.8 × 1.6 m access doorway: bottom edge on the deck, off-centre to port. */
const ACCESS_DOOR_WIDTH = 0.8
const ACCESS_DOOR_HEIGHT = 1.6
const ACCESS_DOOR_CENTER_Y = 0.8
const ACCESS_DOOR_CENTER_X = -1.2

/* ------------------------------------------------------- drive glow window */

/** The §4 landmark: 1.4 × 0.9 m of shielded drive glow beside the access door. */
const WINDOW_WIDTH = 1.4
const WINDOW_HEIGHT = 0.9
const WINDOW_DEPTH = 0.12
const WINDOW_X = 0.9
const WINDOW_Y = 1.55
/** Place it so the frame's BACK lands on the bulkhead face (its own rotation 2
 * turns the grating, which is proud of the frame's +Z face, aft into the room). */
const WINDOW_Z = REACTOR_FACE_Z - WINDOW_DEPTH / 2
/** The window's glow lens is authored AT the primitive origin (glowWindowParts). */
const WINDOW_GLOW_LOCAL: Vec3 = [0, 0, 0]

/* --------------------------------------------------------- radiation placard */

/** The trefoil placard, port of the window and beside the access door. */
const SIGN_WIDTH = 0.4
const SIGN_HEIGHT = 0.5
const SIGN_THICKNESS = 0.02
const SIGN_X = -0.55
const SIGN_Y = 1.7
/** Back flush on the bulkhead face; the mark stands proud into the room. */
const SIGN_Z = REACTOR_FACE_Z - SIGN_THICKNESS / 2

/* ------------------------------------------------------------- heat shielding */

/** Ceramic heat shields, clad either side of the window on the bulkhead face. */
const SHIELD_THICKNESS = 0.04
const SHIELD_HEIGHT = 0.7
const SHIELD_STRIPE_HEIGHT = 0.12
/** Off the face by half the plate PLUS the stripe's own proudness, so the worn
 * stripe never pokes into the bulkhead it is bolted to. */
const SHIELD_Z = REACTOR_FACE_Z - SHIELD_THICKNESS / 2 - 0.005

/* ------------------------------------------------------------------- lockers */

/** Stores locker bank on the port wall, doors into the room (yaw 1). */
const STORES_X = -INNER_X + 0.25
const STORES_Z = -0.9
const STORES_WIDTH = 1.8
const STORES_HEIGHT = 2.0
const STORES_DEPTH = 0.5

/** Spares locker forward of it, on the port side of the reactor bulkhead. */
const SPARES_X = -INNER_X + 0.25
const SPARES_Z = 0.7
const SPARES_WIDTH = 1.0
const SPARES_HEIGHT = 1.8
const SPARES_DEPTH = 0.5

/** Machinery locker against the starboard wall aft of the console bench. */
const MACHINERY_X = INNER_X - 0.25
const MACHINERY_Z = -1.85
const MACHINERY_WIDTH = 0.9
const MACHINERY_HEIGHT = 2.0
const MACHINERY_DEPTH = 0.5

/* ----------------------------------------------------------- console bench */

/** Reactor console: the bench along the starboard wall + its display + task strip. */
const BENCH_X = 1.85
const BENCH_Z = -0.8
const BENCH_LENGTH = 1.2
const BENCH_DEPTH = 0.6
const BENCH_HEIGHT = 0.9
const CONSOLE_SCREEN_Y = 1.85
const CONSOLE_TASK_Y = 1.55
/** Wall-mounted fixtures sit this far off the wall's inner face (half their depth). */
const SCREEN_MOUNT_X = INNER_X - 0.03
const SCREEN_DEPTH = 0.06
const TASK_STRIP_DEPTH = 0.25

/* ------------------------------------------------------------------- lights */

/** Recessed panel lights just below the ceiling (housing top 0.03 m clear). */
const PANEL_Y = HEIGHT - 0.06
/** Exposed conduit runs: a ceiling main, a ceiling branch and two wall runs. */
const CONDUIT_RADIUS = 0.05
const CONDUIT_CLAMP_T = 0.03
const CEILING_MAIN_Y = 2.86
const CEILING_BRANCH_Y = 2.7
const WALL_RUN_Y = 2.5

/* ---------------------------------------------------------------- assemblies */

/** A recessed panel light at the kit's standard size. */
function panelLight(): ModuleAssembly['parts'] {
  return panelLightParts({
    width: 0.6,
    depth: 0.3,
    housingThickness: 0.06,
    lensInset: 0.08,
  })
}

/** A wall screen at the console's size. */
function consoleScreen(): ModuleAssembly['parts'] {
  return screenParts({ width: 0.9, height: 0.5, depth: SCREEN_DEPTH, bezel: 0.03 })
}

/**
 * The engineering module, assembly by assembly. Order is the build order:
 * shell, the two socket hatches, the machinery bay, the reactor bulkhead and
 * its access hatch, the drive glow window, the placard and heat shielding, and
 * finally the practical lighting + routing.
 */
export const ENGINEERING_ASSEMBLIES: readonly ModuleAssembly[] = [
  {
    id: 'deck-plate',
    parts: deckPlateParts({
      width: WIDTH,
      depth: DEPTH,
      thickness: 0.2,
      // Runs are laid clear of both doorway prisms (the aft spine breach at
      // z = −2.4 and the starboard high-hatch at z = 0.6): ±1.9 m only.
      cableRuns: { count: 3, width: 0.12, height: 0.06, spacing: 1.9 },
    }),
    placement: { position: [0, 0, 0] },
    solid: true,
  },
  {
    id: 'wall-aft-spine',
    parts: bulkheadParts({
      width: WIDTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: { width: 0.9, height: 2.0, centerY: STANDARD_DOOR_CENTER_M },
    }),
    placement: { position: [0, 0, -(HALF_Z - WALL_T / 2)] },
    solid: true,
  },
  {
    id: 'wall-fwd',
    parts: bulkheadParts({ width: WIDTH, height: HEIGHT, thickness: WALL_T }),
    placement: { position: [0, 0, HALF_Z - WALL_T / 2] },
    solid: true,
  },
  {
    id: 'wall-port',
    parts: bulkheadParts({ width: DEPTH, height: HEIGHT, thickness: WALL_T }),
    placement: { position: [-WALL_CENTER_X, 0, 0], rotation: PORT_WALL_ROTATION },
    solid: true,
  },
  {
    // Starboard wall, carrying the contract's deliberate non-standard door:
    // yaw 3 puts the panel's local +X along module +Z, so the door's `centerX`
    // IS the socket's bow-ward z offset and `centerY` its 1.2 m deck offset.
    id: 'wall-stbd',
    parts: bulkheadParts({
      width: DEPTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: {
        width: HIGH_HATCH_WIDTH,
        height: HIGH_HATCH_HEIGHT,
        centerY: HIGH_HATCH_CENTER_Y,
        centerX: HIGH_HATCH_Z,
      },
    }),
    placement: { position: [WALL_CENTER_X, 0, 0], rotation: STBD_WALL_ROTATION },
    solid: true,
  },
  {
    // The room's hatch on its spine door (socket-centred: position = door
    // centre, local Z = wall normal). The spine module (M2-T6) brings the
    // shaft and its per-deck sockets — NOT a second hatch.
    id: 'hatch-spine',
    parts: hatchParts({
      door: { width: 0.9, height: 2.0 },
      leafThickness: 0.05,
      frameWidth: 0.05,
      clearance: 0.01,
    }),
    placement: { position: [0, STANDARD_DOOR_CENTER_M, -HALF_Z] },
    fillsSocket: true,
  },
  {
    // …and the room's hatch on the high-hatch, at its own opening size. This is
    // the kit's only non-standard door, so it is also the only hatch whose
    // frame is built from the socket's 0.8 × 1.6 m opening rather than the
    // standard size — seated by socket position, never by freehand arithmetic.
    id: 'hatch-high',
    parts: hatchParts({
      door: { width: HIGH_HATCH_WIDTH, height: HIGH_HATCH_HEIGHT },
      leafThickness: 0.05,
      frameWidth: 0.05,
      clearance: 0.01,
    }),
    placement: {
      position: [HALF_X, HIGH_HATCH_CENTER_Y, HIGH_HATCH_Z],
      rotation: STBD_WALL_ROTATION,
    },
    fillsSocket: true,
  },
  {
    // Stores: a two-door locker bank against the port wall (doors into the room).
    id: 'stores-locker',
    parts: lockerParts({
      width: STORES_WIDTH,
      height: STORES_HEIGHT,
      depth: STORES_DEPTH,
      doors: 2,
      doorThickness: 0.03,
      doorGap: 0.02,
    }),
    placement: { position: [STORES_X, 0, STORES_Z], rotation: PORT_WALL_ROTATION },
    solid: true,
  },
  {
    id: 'spares-locker',
    parts: lockerParts({
      width: SPARES_WIDTH,
      height: SPARES_HEIGHT,
      depth: SPARES_DEPTH,
      doors: 1,
      doorThickness: 0.03,
      doorGap: 0.02,
    }),
    placement: { position: [SPARES_X, 0, SPARES_Z], rotation: PORT_WALL_ROTATION },
    solid: true,
  },
  {
    // Machinery: pumps and spares against the starboard wall, aft of the bench
    // (yaw 3 turns its door face to −x, i.e. out into the room).
    id: 'machinery-locker',
    parts: lockerParts({
      width: MACHINERY_WIDTH,
      height: MACHINERY_HEIGHT,
      depth: MACHINERY_DEPTH,
      doors: 1,
      doorThickness: 0.03,
      doorGap: 0.02,
    }),
    placement: {
      position: [MACHINERY_X, 0, MACHINERY_Z],
      rotation: STBD_WALL_ROTATION,
    },
    solid: true,
  },
  {
    // Console bench along the starboard wall (yaw 1: long axis fore-and-aft).
    id: 'console-bench',
    parts: tableParts({
      width: BENCH_LENGTH,
      depth: BENCH_DEPTH,
      height: BENCH_HEIGHT,
      topThickness: 0.05,
      legRadius: 0.035,
    }),
    placement: { position: [BENCH_X, 0, BENCH_Z], rotation: PORT_WALL_ROTATION },
    solid: true,
  },
  {
    // Console display on the wall above the bench (yaw 3: faces −x).
    id: 'console-screen',
    parts: consoleScreen(),
    placement: {
      position: [SCREEN_MOUNT_X, CONSOLE_SCREEN_Y, BENCH_Z],
      rotation: STBD_WALL_ROTATION,
    },
  },
  {
    // The bench's own task strip light — the room's `task` fixture, recessed
    // into the wall over the bench surface.
    id: 'console-task-light',
    parts: panelLightParts({
      width: 0.5,
      depth: TASK_STRIP_DEPTH,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: {
      position: [INNER_X - 0.05, CONSOLE_TASK_Y, BENCH_Z],
      rotation: STBD_WALL_ROTATION,
    },
  },
  {
    // The reactor bulkhead: the bow end of the room, with the 0.8 × 1.6 m
    // access doorway whose sill is the deck itself.
    id: 'reactor-bulkhead',
    parts: bulkheadParts({
      width: WIDTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: {
        width: ACCESS_DOOR_WIDTH,
        height: ACCESS_DOOR_HEIGHT,
        centerY: ACCESS_DOOR_CENTER_Y,
        centerX: ACCESS_DOOR_CENTER_X,
      },
    }),
    placement: { position: [0, 0, REACTOR_PARTITION_Z] },
    solid: true,
  },
  {
    // The reactor access hatch, socket-centred on the partition's own doorway
    // (an interior opening, not a DoorSocket — so it is not `fillsSocket`).
    id: 'hatch-reactor-access',
    parts: hatchParts({
      door: { width: ACCESS_DOOR_WIDTH, height: ACCESS_DOOR_HEIGHT },
      leafThickness: 0.05,
      frameWidth: 0.05,
      clearance: 0.01,
    }),
    placement: {
      position: [ACCESS_DOOR_CENTER_X, ACCESS_DOOR_CENTER_Y, REACTOR_PARTITION_Z],
    },
  },
  {
    // THE §4 LANDMARK: the drive's glow, seen through a shielded grating in the
    // reactor bulkhead. Yaw 2 turns the window's grating (proud of its +Z face)
    // aft into the room, so the glow is what you walk toward.
    id: 'glow-window',
    parts: glowWindowParts({
      width: WINDOW_WIDTH,
      height: WINDOW_HEIGHT,
      depth: WINDOW_DEPTH,
      frameWidth: 0.06,
      glowInset: 0.06,
      barCount: 5,
      barWidth: 0.06,
      barThickness: 0.03,
    }),
    placement: { position: [WINDOW_X, WINDOW_Y, WINDOW_Z], rotation: 2 },
    solid: true,
  },
  {
    // The radiation placard: hazard plate on the bulkhead, mark proud of it.
    id: 'radiation-sign',
    parts: radiationSignParts({
      width: SIGN_WIDTH,
      height: SIGN_HEIGHT,
      thickness: SIGN_THICKNESS,
      hubRadius: 0.04,
      bladeRadius: 0.07,
      bladeDistance: 0.11,
      markThickness: 0.012,
    }),
    placement: { position: [SIGN_X, SIGN_Y, SIGN_Z], rotation: 2 },
    solid: true,
  },
  {
    // Ceramic heat shielding under the window, its worn hazard stripe on the
    // same plate (§4 "ceramic heat shielding near the drive", "warning striping").
    id: 'heat-shield-stbd',
    parts: heatShieldParts({
      width: 1.6,
      height: SHIELD_HEIGHT,
      thickness: SHIELD_THICKNESS,
      stripeHeight: SHIELD_STRIPE_HEIGHT,
    }),
    placement: { position: [WINDOW_X, 0.5, SHIELD_Z], rotation: 2 },
    solid: true,
  },
  {
    // …and its twin on the port side of the access door.
    id: 'heat-shield-port',
    parts: heatShieldParts({
      width: 0.6,
      height: SHIELD_HEIGHT,
      thickness: SHIELD_THICKNESS,
      stripeHeight: SHIELD_STRIPE_HEIGHT,
    }),
    placement: { position: [-1.95, 0.5, SHIELD_Z], rotation: 2 },
    solid: true,
  },
  {
    id: 'panel-light-aft',
    parts: panelLight(),
    placement: { position: [0.6, PANEL_Y, -1.9] },
  },
  {
    id: 'panel-light-mid',
    parts: panelLight(),
    placement: { position: [-1.0, PANEL_Y, -0.2] },
  },
  {
    id: 'panel-light-reactor',
    parts: panelLight(),
    placement: { position: [0.4, PANEL_Y, 0.9] },
  },
  {
    id: 'conduit-ceiling-main',
    parts: conduitRunParts({
      length: WIDTH - 0.4,
      radius: CONDUIT_RADIUS,
      axis: 'x',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [0, CEILING_MAIN_Y, -1.0] },
  },
  {
    id: 'conduit-ceiling-branch',
    parts: conduitRunParts({
      length: 2.6,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [1.2, CEILING_BRANCH_Y, 0.6] },
  },
  {
    // Port wall run, stopping short of the spine doorway it would otherwise cross.
    id: 'conduit-port',
    parts: conduitRunParts({
      length: 1.6,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 3,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [-INNER_X + CONDUIT_RADIUS, WALL_RUN_Y, -1.5] },
  },
  {
    // Starboard wall run, aft of the high-hatch opening (z ∈ [0.2, 1.0]) and
    // stopped short of the aft bulkhead.
    id: 'conduit-stbd',
    parts: conduitRunParts({
      length: 1.2,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 3,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [INNER_X - CONDUIT_RADIUS, WALL_RUN_Y, -1.75] },
  },
]

/* ------------------------------------------------------------------- anchors */

/** An assembly's module-local placement (throws on a typo'd assembly id). */
function placementOf(assemblyId: string) {
  const assembly = ENGINEERING_ASSEMBLIES.find(
    (candidate) => candidate.id === assemblyId,
  )
  if (assembly === undefined) {
    throw new Error(`engineering module: no assembly "${assemblyId}"`)
  }
  return assembly.placement
}

/**
 * An equipment anchor AT the assembly's own origin — anchors and geometry
 * share one source, so a moved prop moves its anchor with it.
 */
function equipmentSlot(assemblyId: string): EquipmentSlot {
  const { position, rotation } = placementOf(assemblyId)
  return { id: assemblyId, position: position ?? [0, 0, 0], rotation: rotation ?? 0 }
}

/** A light fixture anchor at an assembly's origin (panel lights, displays). */
function lightSocketOf(assemblyId: string, kind: LightKind): LightSocket {
  const { position, rotation } = placementOf(assemblyId)
  return {
    id: assemblyId,
    kind,
    position: position ?? [0, 0, 0],
    rotation: rotation ?? 0,
  }
}

/** The lens offset inside a panel-light primitive (panelLightParts), meters. */
const PANEL_LENS_LOCAL: Vec3 = [0, -0.03, 0]

/**
 * The console's task-light anchor, read off the fixture's OWN emissive part:
 * `panelLightParts` puts the lens 0.03 m below the housing centre, so the
 * socket is that primitive-local point placed through the same transform the
 * parts went through (placePoint) — the M4-T1 rig lights the real lens.
 */
function consoleTaskLight(): LightSocket {
  return {
    id: 'console-task-light',
    kind: 'task',
    position: placePoint(PANEL_LENS_LOCAL, placementOf('console-task-light')),
  }
}

/**
 * The room's `reactor` light: the drive glow itself, anchored on the window's
 * own glow lens (authored at the glow-window primitive's origin), so M4-T1
 * places the reactor light where the glow is drawn rather than near the frame.
 */
function reactorGlow(): LightSocket {
  const placement = placementOf('glow-window')
  return {
    id: 'reactor-glow',
    kind: 'reactor',
    position: placePoint(WINDOW_GLOW_LOCAL, placement),
    rotation: placement.rotation ?? 0,
  }
}

/* -------------------------------------------------------------------- module */

/**
 * The authored engineering module: the M1-T2 manifest entry (contract dims, the
 * standardized spine door + the contract's non-standard high-hatch, the §4
 * landmark anchors, the derived collision hint) plus the assemblies that build
 * it.
 */
export const ENGINEERING_MODULE: AuthoredModule = {
  manifest: {
    id: 'engineering',
    label: 'Engineering (reactor access, drive glow window)',
    dimensions: [WIDTH, HEIGHT, DEPTH],
    doorSockets: [
      // The standardized spine door: −z face, flush, standard 1.0 m centre —
      // exactly the contract origin (src/validation/contractKit.ts).
      {
        id: 'spine-door',
        position: [0, STANDARD_DOOR_CENTER_M, -HALF_Z],
        facing: '-z',
      },
      // The contract's non-standard door — the kit's ONLY declared deck offset
      // (+0.2 m) and its only non-standard opening (0.8 × 1.6 m).
      {
        id: 'high-hatch',
        position: [HALF_X, HIGH_HATCH_CENTER_Y, HIGH_HATCH_Z],
        facing: '+x',
        door: { width: HIGH_HATCH_WIDTH, height: HIGH_HATCH_HEIGHT },
      },
    ],
    lightSockets: [
      lightSocketOf('panel-light-aft', 'panel'),
      lightSocketOf('panel-light-mid', 'panel'),
      lightSocketOf('panel-light-reactor', 'panel'),
      consoleTaskLight(),
      lightSocketOf('console-screen', 'screen'),
      reactorGlow(),
    ],
    equipmentSlots: [
      equipmentSlot('hatch-spine'),
      equipmentSlot('hatch-high'),
      equipmentSlot('stores-locker'),
      equipmentSlot('spares-locker'),
      equipmentSlot('machinery-locker'),
      equipmentSlot('console-bench'),
      equipmentSlot('console-screen'),
      equipmentSlot('console-task-light'),
      equipmentSlot('hatch-reactor-access'),
      equipmentSlot('glow-window'),
      equipmentSlot('radiation-sign'),
      equipmentSlot('heat-shield-stbd'),
      equipmentSlot('heat-shield-port'),
    ],
    collisionHint: { boxes: collisionBoxesFor(ENGINEERING_ASSEMBLIES) },
  },
  assemblies: ENGINEERING_ASSEMBLIES,
}
