/**
 * M2-T3 — the authored GALLEY / BUNK module: the crew's heart.
 *
 * PRD §4 landmark: "The galley/bunk: the mess table and the coffee station —
 * the crew's heart — plus berths and the head." The room is one deck module on
 * the M1-T2 authoring frame — floor at local y = 0, footprint centred on the
 * origin in XZ, the standardized `spine-door` flush in the module's −z face at
 * the standard 1.0 m centre (src/fixtures/layout.ts: every room attaches to
 * the spine's +z face, so the −z face is the centreline breach to the shaft).
 *
 * Reading the room from the spine door (aft, −z) toward the bow (+z):
 *  - the walkway runs straight up the centreline past the berth stack;
 *  - the BERTHS (two high) are stacked on the port wall aft — the bunk alcove;
 *  - the MESS (bolted table + two benches facing it) fills the starboard side;
 *  - the PANTRY locker bank lines the port wall amidships;
 *  - the COFFEE STATION — the §4 warm-accent landmark with the room's one
 *    reserved warm material — is centred on the forward wall, facing the
 *    spine door: it is what you see walking in, and it is deliberately the
 *    only coffee-accent geometry in the module;
 *  - the HEAD (toilet/shower) is a partition-built stall in the forward-port
 *    corner, entered through a 0.7 × 1.9 m doorway in its aft partition.
 *
 * The starboard wall carries the contract's `side-door` socket (M1-T3
 * contractKit) — a door off-centre along the wall, so the wall panel is cut
 * with the bulkhead builder's `door.centerX` (never freehand geometry,
 * BUILD_PLAN rule 8) and the opening is sealed with a socket-centred hatch the
 * same way the spine door is. Both hatches belong to the room; the M2-T6 spine
 * module supplies the shaft + per-deck sockets and adds NO hatch of its own.
 *
 * Everything is generated by the M2-T1 builders and placed through
 * `placePart` / `placePoint`; `GALLEY_ASSEMBLIES` is the authored truth, and
 * the anchors (light sockets, equipment slots) are DERIVED from those
 * placements so they can never drift from the geometry. The manifest's
 * collision hint is derived the same way (`collisionBoxesFor`).
 */

import { DECK_CLEAR_M, STANDARD_DOOR_CENTER_M } from '../../types'
import type { EquipmentSlot, LightKind, LightSocket, Vec3 } from '../../types'
import {
  bulkheadParts,
  coffeeStationParts,
  conduitRunParts,
  couchParts,
  deckPlateParts,
  hatchParts,
  lockerParts,
  panelLightParts,
  screenParts,
  tableParts,
} from '../parts'
import { placePoint } from './placement'
import { collisionBoxesFor } from './types'
import type { AuthoredModule, ModuleAssembly } from './types'

/* ----------------------------------------------------------------- geometry */

/** Galley-module box [width, height, depth] m — the M0-T5 contract footprint. */
const WIDTH = 4.2
const DEPTH = 5.0
const HEIGHT = DECK_CLEAR_M
const HALF_X = WIDTH / 2
const HALF_Z = DEPTH / 2

/** Bulkhead thickness (kit default), m. */
const WALL_T = 0.1
/** Wall centre planes (flush with the module faces) and the room's inner faces. */
const WALL_CENTER_X = HALF_X - WALL_T / 2
const INNER_X = HALF_X - WALL_T
const INNER_Z = HALF_Z - WALL_T

/**
 * Lateral rotation that reads "along the room": a bulkhead placed with yaw 3
 * has its local +X running along module +Z (rotY turns (x, z) → (−z, x)), so
 * a panel's width, its `door.centerX` and anything else authored along it
 * read directly as bow-ward (+z) offsets. The starboard wall carries the
 * contract's off-centre `side-door`, so it is authored this way.
 */
const STBD_WALL_ROTATION = 3 as const

/* ----------------------------------------------------------------- sockets */

/** The contract's side door: +x face, standard centre, 1.2 m bow-ward of centre. */
const SIDE_DOOR_Z = 1.2

/* ------------------------------------------------------------------ berths */

/** Two berths, stacked: the lower on the deck, the upper 0.95 m above it. */
const BUNK_X = -1.55
const BUNK_Z = -1.4
const BUNK_WIDTH = 0.8
const BUNK_LENGTH = 1.9
const BUNK_MATTRESS_Y = 0.45
const BUNK_UPPER_Y = 0.95

/* -------------------------------------------------------------------- mess */

/** Table + two benches facing it, on the starboard side aft of the side door. */
const TABLE_X = 1.2
const TABLE_Z = -0.35
const TABLE_WIDTH = 1.3
const TABLE_DEPTH = 0.7
const BENCH_WIDTH = 1.3
const BENCH_DEPTH = 0.45
const BENCH_SEAT_Y = 0.45
const BENCH_BACK_Y = 0.4
const BENCH_AFT_Z = -1.0
const BENCH_FWD_Z = 0.3

/* ------------------------------------------------------------------ pantry */

const PANTRY_X = -1.775
const PANTRY_Z = 0.4
const PANTRY_WIDTH = 1.6
const PANTRY_DEPTH = 0.45

/* ------------------------------------------------------------------ coffee */

/**
 * The coffee station — the §4 landmark — centred on the forward wall, facing
 * the spine door (yaw 2: its local +z, the side the carafe, accent backsplash
 * and task-light strip are on, turns to face module −z, i.e. the entry).
 */
const COFFEE_WIDTH = 1.0
const COFFEE_HEIGHT = 0.95
const COFFEE_DEPTH = 0.6
const COFFEE_X = 0.7
const COFFEE_Z = INNER_Z - COFFEE_DEPTH / 2
const COFFEE_ROTATION = 2 as const
/** The station's own task-light strip, primitive-local (coffeeStationParts). */
const COFFEE_STRIP_LOCAL: Vec3 = [0, COFFEE_HEIGHT - 0.08, COFFEE_DEPTH / 2 + 0.025]

/* -------------------------------------------------------------------- head */

/**
 * The head: a stall in the forward-port corner, walled off by two bulkhead
 * partitions — one across the room at z = 1.4 (carrying the 0.7 × 1.9 m
 * doorway) and one returning to the forward wall at x = −0.55.
 */
const HEAD_DOOR_WIDTH = 0.7
const HEAD_DOOR_HEIGHT = 1.9
const HEAD_DOOR_CENTER_Y = 0.95
/** Across-the-room partition: spans x ∈ [−2.0, −0.6] at z = 1.4. */
const HEAD_AFT_WIDTH = 1.4
const HEAD_AFT_X = -1.3
const HEAD_AFT_Z = 1.4
/** Return partition: x ∈ [−0.6, −0.5], spanning z ∈ [1.35, 2.45]. */
const HEAD_SIDE_WIDTH = 1.1
const HEAD_SIDE_X = -0.55
const HEAD_SIDE_Z = 1.9
/** Fittings: a sink counter and a plumbing/linen cabinet, plus a mirror. */
const HEAD_COUNTER_X = -1.7
const HEAD_COUNTER_Z = 2.175
const HEAD_MIRROR_Y = 1.6
const HEAD_CABINET_X = -0.75
const HEAD_CABINET_Z = 1.9
const HEAD_CABINET_WIDTH = 0.6
const HEAD_CABINET_HEIGHT = 1.6
const HEAD_CABINET_DEPTH = 0.3

/* ------------------------------------------------------------------- lights */

/** Recessed panel lights just below the ceiling (housing top 0.03 m clear). */
const PANEL_Y = HEIGHT - 0.06
/** Exposed conduit runs: a ceiling main, a ceiling branch and two wall runs. */
const CONDUIT_RADIUS = 0.05
const CONDUIT_CLAMP_T = 0.03
const CEILING_MAIN_Y = 2.86
const CEILING_BRANCH_Y = 2.7
const WALL_RUN_Y = 2.5

/* ---------------------------------------------------------------- assemblies */

/** One stacked berth: the couch primitive read as a bunk (webbing straps). */
function berth(): ModuleAssembly['parts'] {
  return couchParts({
    width: BUNK_WIDTH,
    depth: BUNK_LENGTH,
    seatHeight: BUNK_MATTRESS_Y,
    backHeight: 0.45,
    straps: 2,
  })
}

/**
 * The galley/bunk, assembly by assembly. Order is the build order: shell, the
 * two socket hatches, the berth alcove, the mess, the pantry, the coffee
 * station, the head stall, and finally the practical lighting + routing.
 */
export const GALLEY_ASSEMBLIES: readonly ModuleAssembly[] = [
  {
    id: 'deck-plate',
    parts: deckPlateParts({
      width: WIDTH,
      depth: DEPTH,
      thickness: 0.2,
      // Runs are laid clear of both doorway prisms (the aft spine breach and
      // the starboard side door at z = 1.2): ±1.9 m only.
      cableRuns: { count: 3, width: 0.12, height: 0.06, spacing: 1.9 },
    }),
    placement: { position: [0, 0, 0] },
    solid: true,
  },
  {
    id: 'wall-aft-spine',
    parts: bulkheadParts({
      width: WIDTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: { width: 0.9, height: 2.0, centerY: STANDARD_DOOR_CENTER_M },
    }),
    placement: { position: [0, 0, -(HALF_Z - WALL_T / 2)] },
    solid: true,
  },
  {
    id: 'wall-fwd',
    parts: bulkheadParts({ width: WIDTH, height: HEIGHT, thickness: WALL_T }),
    placement: { position: [0, 0, HALF_Z - WALL_T / 2] },
    solid: true,
  },
  {
    id: 'wall-port',
    parts: bulkheadParts({ width: DEPTH, height: HEIGHT, thickness: WALL_T }),
    placement: { position: [-WALL_CENTER_X, 0, 0], rotation: 1 },
    solid: true,
  },
  {
    // Starboard wall, with the contract's off-centre `side-door` opening cut
    // into it: yaw 3 puts the panel's local +X along module +Z, so the door's
    // `centerX` IS the socket's bow-ward z offset.
    id: 'wall-stbd',
    parts: bulkheadParts({
      width: DEPTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: {
        width: 0.9,
        height: 2.0,
        centerY: STANDARD_DOOR_CENTER_M,
        centerX: SIDE_DOOR_Z,
      },
    }),
    placement: { position: [WALL_CENTER_X, 0, 0], rotation: STBD_WALL_ROTATION },
    solid: true,
  },
  {
    // The room's hatch on its spine door (socket-centred: position = door
    // centre, local Z = wall normal). The spine module (M2-T6) brings the
    // shaft and its per-deck sockets — NOT a second hatch.
    id: 'hatch-spine',
    parts: hatchParts({
      door: { width: 0.9, height: 2.0 },
      leafThickness: 0.05,
      frameWidth: 0.05,
      clearance: 0.01,
    }),
    placement: { position: [0, STANDARD_DOOR_CENTER_M, -HALF_Z] },
    fillsSocket: true,
  },
  {
    // …and the room's hatch on the side door, the same way.
    id: 'hatch-side',
    parts: hatchParts({
      door: { width: 0.9, height: 2.0 },
      leafThickness: 0.05,
      frameWidth: 0.05,
      clearance: 0.01,
    }),
    placement: {
      position: [HALF_X, STANDARD_DOOR_CENTER_M, SIDE_DOOR_Z],
      rotation: STBD_WALL_ROTATION,
    },
    fillsSocket: true,
  },
  {
    id: 'bunk-lower',
    parts: berth(),
    placement: { position: [BUNK_X, 0, BUNK_Z] },
    solid: true,
  },
  {
    id: 'bunk-upper',
    parts: berth(),
    placement: { position: [BUNK_X, BUNK_UPPER_Y, BUNK_Z] },
    solid: true,
  },
  {
    id: 'mess-table',
    parts: tableParts({
      width: TABLE_WIDTH,
      depth: TABLE_DEPTH,
      height: 0.75,
      topThickness: 0.05,
      legRadius: 0.03,
    }),
    placement: { position: [TABLE_X, 0, TABLE_Z] },
    solid: true,
  },
  {
    // Bench seat facing +z: the couch primitive with no straps, its backrest
    // on the aft side, so the two benches flank the table.
    id: 'bench-aft',
    parts: couchParts({
      width: BENCH_WIDTH,
      depth: BENCH_DEPTH,
      seatHeight: BENCH_SEAT_Y,
      backHeight: BENCH_BACK_Y,
      straps: 0,
    }),
    placement: { position: [TABLE_X, 0, BENCH_AFT_Z] },
    solid: true,
  },
  {
    id: 'bench-fwd',
    parts: couchParts({
      width: BENCH_WIDTH,
      depth: BENCH_DEPTH,
      seatHeight: BENCH_SEAT_Y,
      backHeight: BENCH_BACK_Y,
      straps: 0,
    }),
    placement: { position: [TABLE_X, 0, BENCH_FWD_Z], rotation: 2 },
    solid: true,
  },
  {
    // Pantry stores against the port wall (yaw 1: the door face turns to +x).
    id: 'pantry-locker',
    parts: lockerParts({
      width: PANTRY_WIDTH,
      height: 2.0,
      depth: PANTRY_DEPTH,
      doors: 2,
      doorThickness: 0.03,
      doorGap: 0.02,
    }),
    placement: { position: [PANTRY_X, 0, PANTRY_Z], rotation: 1 },
    solid: true,
  },
  {
    // The landmark: coffee station on the forward wall, facing the entry. It
    // is the module's ONLY coffee-accent geometry (gated in galley.test.ts).
    id: 'coffee-station',
    parts: coffeeStationParts({
      width: COFFEE_WIDTH,
      height: COFFEE_HEIGHT,
      depth: COFFEE_DEPTH,
      accentThickness: 0.04,
      carafeRadius: 0.07,
      carafeHeight: 0.22,
    }),
    placement: {
      position: [COFFEE_X, 0, COFFEE_Z],
      rotation: COFFEE_ROTATION,
    },
    solid: true,
  },
  {
    id: 'partition-head-aft',
    parts: bulkheadParts({
      width: HEAD_AFT_WIDTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: {
        width: HEAD_DOOR_WIDTH,
        height: HEAD_DOOR_HEIGHT,
        centerY: HEAD_DOOR_CENTER_Y,
      },
    }),
    placement: { position: [HEAD_AFT_X, 0, HEAD_AFT_Z] },
    solid: true,
  },
  {
    id: 'partition-head-stbd',
    parts: bulkheadParts({
      width: HEAD_SIDE_WIDTH,
      height: HEIGHT,
      thickness: WALL_T,
    }),
    placement: {
      position: [HEAD_SIDE_X, 0, HEAD_SIDE_Z],
      rotation: STBD_WALL_ROTATION,
    },
    solid: true,
  },
  {
    id: 'head-counter',
    parts: tableParts({
      width: 0.6,
      depth: 0.45,
      height: 0.85,
      topThickness: 0.04,
      legRadius: 0.025,
    }),
    placement: { position: [HEAD_COUNTER_X, 0, HEAD_COUNTER_Z] },
    solid: true,
  },
  {
    // Plumbing / linen cabinet against the return partition's inner face
    // (yaw 3: its door face turns to −x, into the stall).
    id: 'head-cabinet',
    parts: lockerParts({
      width: HEAD_CABINET_WIDTH,
      height: HEAD_CABINET_HEIGHT,
      depth: HEAD_CABINET_DEPTH,
      doors: 1,
      doorThickness: 0.03,
      doorGap: 0.02,
    }),
    placement: {
      position: [HEAD_CABINET_X, 0, HEAD_CABINET_Z],
      rotation: STBD_WALL_ROTATION,
    },
    solid: true,
  },
  {
    // Mirror (the glass/screen slot) over the sink, on the port wall — yaw 1
    // turns its emissive face into the stall.
    id: 'head-mirror',
    parts: screenParts({ width: 0.6, height: 0.45, depth: 0.06, bezel: 0.03 }),
    placement: {
      position: [-INNER_X + 0.03, HEAD_MIRROR_Y, HEAD_COUNTER_Z],
      rotation: 1,
    },
  },
  {
    // Mess display on the starboard wall above the table — the crew's status
    // board, and the module's `screen` light source (yaw 3: faces −x, into
    // the room).
    id: 'mess-screen',
    parts: screenParts({ width: 0.9, height: 0.5, depth: 0.06, bezel: 0.03 }),
    placement: {
      position: [INNER_X - 0.03, 1.8, TABLE_Z],
      rotation: STBD_WALL_ROTATION,
    },
  },
  {
    id: 'panel-light-bunk',
    parts: panelLightParts({
      width: 0.6,
      depth: 0.3,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: { position: [BUNK_X, PANEL_Y, BUNK_Z] },
  },
  {
    id: 'panel-light-mess',
    parts: panelLightParts({
      width: 0.6,
      depth: 0.3,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: { position: [TABLE_X, PANEL_Y, TABLE_Z] },
  },
  {
    id: 'panel-light-galley',
    parts: panelLightParts({
      width: 0.6,
      depth: 0.3,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: { position: [COFFEE_X, PANEL_Y, 1.5] },
  },
  {
    id: 'panel-light-head',
    parts: panelLightParts({
      width: 0.6,
      depth: 0.3,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: { position: [HEAD_AFT_X, PANEL_Y, HEAD_SIDE_Z] },
  },
  {
    id: 'conduit-ceiling-main',
    parts: conduitRunParts({
      length: WIDTH - 0.4,
      radius: CONDUIT_RADIUS,
      axis: 'x',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [0, CEILING_MAIN_Y, -1.2] },
  },
  {
    id: 'conduit-ceiling-branch',
    parts: conduitRunParts({
      length: DEPTH - 0.8,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 5,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [1.6, CEILING_BRANCH_Y, 0.3] },
  },
  {
    // Port wall run, stopped short of the head stall it would otherwise
    // cross (z = 1.35).
    id: 'conduit-port',
    parts: conduitRunParts({
      length: 3.4,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [-INNER_X + CONDUIT_RADIUS, WALL_RUN_Y, -0.65] },
  },
  {
    // Starboard wall run, stopped short of the side-door opening (z = 0.75).
    id: 'conduit-stbd',
    parts: conduitRunParts({
      length: 3.0,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [INNER_X - CONDUIT_RADIUS, WALL_RUN_Y, -0.8] },
  },
]

/* ------------------------------------------------------------------- anchors */

/** An assembly's module-local placement (throws on a typo'd assembly id). */
function placementOf(assemblyId: string) {
  const assembly = GALLEY_ASSEMBLIES.find((candidate) => candidate.id === assemblyId)
  if (assembly === undefined) {
    throw new Error(`galley module: no assembly "${assemblyId}"`)
  }
  return assembly.placement
}

/**
 * An equipment anchor AT the assembly's own origin — anchors and geometry
 * share one source, so a moved prop moves its anchor with it.
 */
function equipmentSlot(assemblyId: string): EquipmentSlot {
  const { position, rotation } = placementOf(assemblyId)
  return { id: assemblyId, position: position ?? [0, 0, 0], rotation: rotation ?? 0 }
}

/** A light fixture anchor at an assembly's origin (panel lights, displays). */
function lightSocketOf(assemblyId: string, kind: LightKind): LightSocket {
  const { position, rotation } = placementOf(assemblyId)
  return {
    id: assemblyId,
    kind,
    position: position ?? [0, 0, 0],
    rotation: rotation ?? 0,
  }
}

/**
 * The coffee station's task-light anchor, read off the station's OWN geometry:
 * `coffeeStationParts` hangs its strip light on the cabinet's front face, so
 * the socket is that primitive-local point placed through the same transform
 * the parts went through (placePoint) — the M4-T1 rig lights the real fixture.
 */
function coffeeTaskLight(): LightSocket {
  return {
    id: 'coffee-station-task',
    kind: 'task',
    position: placePoint(COFFEE_STRIP_LOCAL, placementOf('coffee-station')),
  }
}

/* ------------------------------------------------------------------- module */

/**
 * The authored galley/bunk module: the M1-T2 manifest entry (contract dims,
 * the standardized spine door + the contract side door, the §4 landmark
 * anchors, the derived collision hint) plus the assemblies that build it.
 */
export const GALLEY_MODULE: AuthoredModule = {
  manifest: {
    id: 'galley',
    label: 'Galley / bunk (mess table + coffee station landmark, berths, head)',
    dimensions: [WIDTH, HEIGHT, DEPTH],
    doorSockets: [
      // The standardized spine door: −z face, flush, standard 1.0 m centre —
      // exactly the contract origin (src/validation/contractKit.ts).
      {
        id: 'spine-door',
        position: [0, STANDARD_DOOR_CENTER_M, -HALF_Z],
        facing: '-z',
      },
      // The contract's side door: +x face, standard centre, 1.2 m bow-ward.
      {
        id: 'side-door',
        position: [HALF_X, STANDARD_DOOR_CENTER_M, SIDE_DOOR_Z],
        facing: '+x',
      },
    ],
    lightSockets: [
      lightSocketOf('panel-light-bunk', 'panel'),
      lightSocketOf('panel-light-mess', 'panel'),
      lightSocketOf('panel-light-galley', 'panel'),
      lightSocketOf('panel-light-head', 'panel'),
      coffeeTaskLight(),
      lightSocketOf('mess-screen', 'screen'),
    ],
    equipmentSlots: [
      equipmentSlot('hatch-spine'),
      equipmentSlot('hatch-side'),
      equipmentSlot('bunk-lower'),
      equipmentSlot('bunk-upper'),
      equipmentSlot('mess-table'),
      equipmentSlot('bench-aft'),
      equipmentSlot('bench-fwd'),
      equipmentSlot('pantry-locker'),
      equipmentSlot('coffee-station'),
      equipmentSlot('head-counter'),
      equipmentSlot('head-cabinet'),
      equipmentSlot('head-mirror'),
      equipmentSlot('mess-screen'),
    ],
    collisionHint: { boxes: collisionBoxesFor(GALLEY_ASSEMBLIES) },
  },
  assemblies: GALLEY_ASSEMBLIES,
}
