/**
 * M2-T2 — the authored HEAD module: the bridge.
 *
 * PRD §4 landmark: "The head (bridge): two crash-couch stations facing a
 * sensor-wall display, pilot/gunner consoles." The room is one deck module on
 * the M1-T2 authoring frame — floor at local y = 0, footprint centred on the
 * origin in XZ, the standardized `spine-door` flush in the module's −z face at
 * the standard 1.0 m centre (src/fixtures/layout.ts: every room attaches to
 * the spine's +z face, so the −z face is the centreline breach to the shaft).
 *
 * Bow (+z) is the sensor wall: the two crash couches face it, each with its
 * console desk between the seat and the wall and its station display above the
 * desk; the main sensor array spans the centreline above them. The spine door
 * is aft (−z) and the walkway from it runs up the centreline between the two
 * stations to the sensor wall — the M0-T1 wayfinding read on entering the
 * bridge. A locker bank and the exposed service routing (ceiling + side-wall
 * conduit runs) fill out the §4 "worn and utilitarian" read, lit only by the
 * panel lights and the displays' emissives (no sun — practical lighting only).
 *
 * Everything is generated by the M2-T1 builders (rule 8) and placed through
 * `placePart`; `HEAD_ASSEMBLIES` is the authored truth. The manifest's
 * collision hint is derived from the same assemblies (`collisionBoxesFor`), so
 * the M3-T3 hull can never drift from the geometry the walkthrough renders.
 */

import { DECK_CLEAR_M, STANDARD_DOOR_CENTER_M } from '../../types'
import type { EquipmentSlot, LightKind, LightSocket } from '../../types'
import {
  bulkheadParts,
  conduitRunParts,
  couchParts,
  deckPlateParts,
  hatchParts,
  lockerParts,
  panelLightParts,
  screenParts,
  tableParts,
} from '../parts'
import { collisionBoxesFor } from './types'
import type { AuthoredModule, ModuleAssembly } from './types'

/* ----------------------------------------------------------------- geometry */

/** Head-module box [width, height, depth] m — the M0-T5 contract footprint. */
const WIDTH = 4.8
const DEPTH = 3.6
const HEIGHT = DECK_CLEAR_M
const HALF_X = WIDTH / 2
const HALF_Z = DEPTH / 2

/** Bulkhead thickness (kit default), m. */
const WALL_T = 0.1
/** Wall centre planes (flush with the module faces) and the room's inner faces. */
const WALL_CENTER_X = HALF_X - WALL_T / 2
const INNER_X = HALF_X - WALL_T
const INNER_Z = HALF_Z - WALL_T

/** Crash-couch stations: one per side of the centreline walkway, aft of centre. */
const COUCH_X = 1.2
const COUCH_Z = 0.55
/** Console desks: in front of each couch, bolted against the sensor wall. */
const CONSOLE_Z = INNER_Z - 0.25
const CONSOLE_TASK_Y = 1.05

/** Displays: mounted flush on the sensor wall's inner face, facing −z. */
const SCREEN_DEPTH = 0.06
const SCREEN_MOUNT_Z = INNER_Z - SCREEN_DEPTH / 2
const SENSOR_Y = 2.2
const STATION_SCREEN_Y = 1.5

/** Locker bank: back flush against the port wall, aft of the stations. */
const LOCKER_DEPTH = 0.45
const LOCKER_X = -INNER_X + LOCKER_DEPTH / 2
const LOCKER_Z = -0.9

/** Recessed panel lights just below the ceiling (housing top 0.03 m clear). */
const PANEL_Y = HEIGHT - 0.06

/** Exposed conduit runs along the ceiling and both side walls. */
const CONDUIT_RADIUS = 0.05
const CONDUIT_CLAMP_T = 0.03
const CEILING_CONDUIT_Y = 2.86
const CEILING_CONDUIT_Z = -1.5
const SIDE_CONDUIT_X = 2.2
const SIDE_CONDUIT_Y = 2.6

/* ---------------------------------------------------------------- assemblies */

/**
 * The bridge, assembly by assembly. Order is the build order: shell, then the
 * spine hatch, then the seats and consoles, the displays, the locker bank, and
 * finally the practical lighting + service routing.
 */
export const HEAD_ASSEMBLIES: readonly ModuleAssembly[] = [
  {
    id: 'deck-plate',
    parts: deckPlateParts({
      width: WIDTH,
      depth: DEPTH,
      thickness: 0.2,
      cableRuns: { count: 3, width: 0.12, height: 0.06, spacing: 1.2 },
    }),
    placement: { position: [0, 0, 0] },
    solid: true,
  },
  {
    id: 'wall-aft-spine',
    parts: bulkheadParts({
      width: WIDTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: { width: 0.9, height: 2.0, centerY: STANDARD_DOOR_CENTER_M },
    }),
    placement: { position: [0, 0, -(HALF_Z - WALL_T / 2)] },
    solid: true,
  },
  {
    id: 'wall-fwd-sensor',
    parts: bulkheadParts({ width: WIDTH, height: HEIGHT, thickness: WALL_T }),
    placement: { position: [0, 0, HALF_Z - WALL_T / 2] },
    solid: true,
  },
  {
    id: 'wall-port',
    parts: bulkheadParts({ width: DEPTH, height: HEIGHT, thickness: WALL_T }),
    placement: { position: [-WALL_CENTER_X, 0, 0], rotation: 1 },
    solid: true,
  },
  {
    id: 'wall-stbd',
    parts: bulkheadParts({ width: DEPTH, height: HEIGHT, thickness: WALL_T }),
    placement: { position: [WALL_CENTER_X, 0, 0], rotation: 1 },
    solid: true,
  },
  {
    // The room's own hatch, seated ON the spine-door socket (socket-centred:
    // position = door centre, local Z = wall normal). The spine module (M2-T6)
    // brings the shaft and its per-deck sockets — NOT a second hatch.
    id: 'hatch-spine',
    parts: hatchParts({
      door: { width: 0.9, height: 2.0 },
      leafThickness: 0.05,
      frameWidth: 0.05,
      clearance: 0.01,
    }),
    placement: { position: [0, STANDARD_DOOR_CENTER_M, -HALF_Z] },
    fillsSocket: true,
  },
  {
    id: 'couch-pilot',
    parts: couchParts({
      width: 0.8,
      depth: 0.9,
      seatHeight: 0.5,
      backHeight: 0.7,
      straps: 3,
    }),
    placement: { position: [-COUCH_X, 0, COUCH_Z] },
    solid: true,
  },
  {
    id: 'couch-gunner',
    parts: couchParts({
      width: 0.8,
      depth: 0.9,
      seatHeight: 0.5,
      backHeight: 0.7,
      straps: 3,
    }),
    placement: { position: [COUCH_X, 0, COUCH_Z] },
    solid: true,
  },
  {
    id: 'console-pilot',
    parts: tableParts({
      width: 1.0,
      depth: 0.5,
      height: 0.75,
      topThickness: 0.05,
      legRadius: 0.03,
    }),
    placement: { position: [-COUCH_X, 0, CONSOLE_Z] },
    solid: true,
  },
  {
    id: 'console-gunner',
    parts: tableParts({
      width: 1.0,
      depth: 0.5,
      height: 0.75,
      topThickness: 0.05,
      legRadius: 0.03,
    }),
    placement: { position: [COUCH_X, 0, CONSOLE_Z] },
    solid: true,
  },
  {
    id: 'sensor-array',
    parts: screenParts({ width: 1.6, height: 0.9, depth: SCREEN_DEPTH, bezel: 0.03 }),
    placement: { position: [0, SENSOR_Y, SCREEN_MOUNT_Z], rotation: 2 },
  },
  {
    id: 'station-screen-port',
    parts: screenParts({ width: 0.7, height: 0.45, depth: SCREEN_DEPTH, bezel: 0.03 }),
    placement: { position: [-COUCH_X, STATION_SCREEN_Y, SCREEN_MOUNT_Z], rotation: 2 },
  },
  {
    id: 'station-screen-stbd',
    parts: screenParts({ width: 0.7, height: 0.45, depth: SCREEN_DEPTH, bezel: 0.03 }),
    placement: { position: [COUCH_X, STATION_SCREEN_Y, SCREEN_MOUNT_Z], rotation: 2 },
  },
  {
    id: 'locker-bank',
    parts: lockerParts({
      width: 0.9,
      height: 2.0,
      depth: LOCKER_DEPTH,
      doors: 2,
      doorThickness: 0.03,
      doorGap: 0.02,
    }),
    placement: { position: [LOCKER_X, 0, LOCKER_Z], rotation: 1 },
    solid: true,
  },
  {
    id: 'panel-light-1',
    parts: panelLightParts({
      width: 0.6,
      depth: 0.3,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: { position: [-1.4, PANEL_Y, 0.6] },
  },
  {
    id: 'panel-light-2',
    parts: panelLightParts({
      width: 0.6,
      depth: 0.3,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: { position: [1.4, PANEL_Y, 0.6] },
  },
  {
    id: 'panel-light-3',
    parts: panelLightParts({
      width: 0.6,
      depth: 0.3,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: { position: [0, PANEL_Y, -1.0] },
  },
  {
    id: 'conduit-ceiling',
    parts: conduitRunParts({
      length: WIDTH - 0.4,
      radius: CONDUIT_RADIUS,
      axis: 'x',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [0, CEILING_CONDUIT_Y, CEILING_CONDUIT_Z] },
  },
  {
    id: 'conduit-port',
    parts: conduitRunParts({
      length: DEPTH - 0.4,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [-SIDE_CONDUIT_X, SIDE_CONDUIT_Y, 0] },
  },
  {
    id: 'conduit-stbd',
    parts: conduitRunParts({
      length: DEPTH - 0.4,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [SIDE_CONDUIT_X, SIDE_CONDUIT_Y, 0] },
  },
]

/* ------------------------------------------------------------------- anchors */

/** An assembly's module-local placement (throws on a typo'd assembly id). */
function placementOf(assemblyId: string) {
  const assembly = HEAD_ASSEMBLIES.find((candidate) => candidate.id === assemblyId)
  if (assembly === undefined) {
    throw new Error(`head module: no assembly "${assemblyId}"`)
  }
  return assembly.placement
}

/**
 * An equipment anchor AT the assembly's own origin — anchors and geometry
 * share one source, so a moved prop moves its anchor with it.
 */
function equipmentSlot(assemblyId: string): EquipmentSlot {
  const { position, rotation } = placementOf(assemblyId)
  return { id: assemblyId, position: position ?? [0, 0, 0], rotation: rotation ?? 0 }
}

/** A light fixture anchor at an assembly's origin (panel lights, displays). */
function lightSocketOf(assemblyId: string, kind: LightKind): LightSocket {
  const { position, rotation } = placementOf(assemblyId)
  return {
    id: assemblyId,
    kind,
    position: position ?? [0, 0, 0],
    rotation: rotation ?? 0,
  }
}

/* ------------------------------------------------------------------- module */

/**
 * The authored head module: the M1-T2 manifest entry (contract dims, the one
 * standardized spine door, the §4 landmark anchors, the derived collision
 * hint) plus the assemblies that build it.
 */
export const HEAD_MODULE: AuthoredModule = {
  manifest: {
    id: 'head',
    label: 'Bridge / head (crash couches, sensor wall, consoles)',
    dimensions: [WIDTH, HEIGHT, DEPTH],
    doorSockets: [
      // The standardized spine door: −z face, flush, standard 1.0 m centre —
      // exactly the contract origin (src/validation/contractKit.ts).
      {
        id: 'spine-door',
        position: [0, STANDARD_DOOR_CENTER_M, -HALF_Z],
        facing: '-z',
      },
    ],
    lightSockets: [
      lightSocketOf('panel-light-1', 'panel'),
      lightSocketOf('panel-light-2', 'panel'),
      lightSocketOf('panel-light-3', 'panel'),
      lightSocketOf('sensor-array', 'screen'),
      lightSocketOf('station-screen-port', 'screen'),
      lightSocketOf('station-screen-stbd', 'screen'),
      {
        id: 'console-task-port',
        kind: 'task',
        position: [-COUCH_X, CONSOLE_TASK_Y, CONSOLE_Z],
      },
      {
        id: 'console-task-stbd',
        kind: 'task',
        position: [COUCH_X, CONSOLE_TASK_Y, CONSOLE_Z],
      },
    ],
    equipmentSlots: [
      equipmentSlot('hatch-spine'),
      equipmentSlot('couch-pilot'),
      equipmentSlot('couch-gunner'),
      equipmentSlot('console-pilot'),
      equipmentSlot('console-gunner'),
      equipmentSlot('sensor-array'),
      equipmentSlot('locker-bank'),
    ],
    collisionHint: { boxes: collisionBoxesFor(HEAD_ASSEMBLIES) },
  },
  assemblies: HEAD_ASSEMBLIES,
}
