/**
 * M2-T4 — the authored OPS module: the airlock, the suit locker, the workbench
 * and the med bay.
 *
 * PRD §4 landmarks: "The airlock & suit locker: interior hatch, two vac suits
 * on racks, tool wall." and "The med bay: fold-down exam bed, med cabinet,
 * red cross-free hazard-adjacent styling." The room is one deck module on the
 * M1-T2 authoring frame — floor at local y = 0, footprint centred on the
 * origin in XZ, the standardized `spine-door` flush in the module's −z face at
 * the standard 1.0 m centre (src/fixtures/layout.ts: every room attaches to
 * the spine's +z face, so the −z face is the centreline breach to the shaft).
 *
 * Reading the room from the spine door (aft, −z) toward the bow (+z):
 *  - the AIRLOCK is the walled-off vestibule in the aft-port corner: two
 *    partitions close it off, its interior hatch is the only way in, its outer
 *    door is the contract's `side-door` in the port face, and inside it hang
 *    the two vac suits on their rack (§4). The vestibule is deliberately
 *    cramped — it is the ship's airlock, not a locker room;
 *  - the TOOL WALL (a bank of tool cabinets) is bolted to the room side of the
 *    airlock's starboard partition, right where you turn to suit up;
 *  - the WORKBENCH runs along the starboard wall amidships: a bolted bench with
 *    its own task strip light and a terminal screen;
 *  - the MED BAY fills the bow-starboard corner: a fold-down exam bed with a
 *    med cabinet on the forward wall and the med monitor above the bed;
 *  - the centreline walk is kept clear from the spine door to the forward wall.
 *
 * The port wall carries the contract's `side-door` socket (M1-T3 contractKit)
 * — off-centre along the wall and facing −x — so the wall panel is cut with the
 * bulkhead builder's `door.centerX` (never freehand geometry, BUILD_PLAN
 * rule 8) and the opening is sealed with a socket-centred hatch, the same way
 * the spine door is. Both hatches belong to the room; the M2-T6 spine module
 * supplies the shaft + per-deck sockets and adds NO hatch of its own.
 *
 * Everything is generated by the M2-T1 builders and placed through `placePart`
 * / `placePoint`; `OPS_ASSEMBLIES` is the authored truth, and the anchors
 * (light sockets, equipment slots) are DERIVED from those placements so they
 * can never drift from the geometry. The manifest's collision hint is derived
 * the same way (`collisionBoxesFor`).
 */

import { DECK_CLEAR_M, STANDARD_DOOR_CENTER_M } from '../../types'
import type { EquipmentSlot, LightKind, LightSocket, Vec3 } from '../../types'
import {
  bulkheadParts,
  conduitRunParts,
  couchParts,
  deckPlateParts,
  hatchParts,
  lockerParts,
  panelLightParts,
  screenParts,
  suitRackParts,
  tableParts,
} from '../parts'
import { placePoint } from './placement'
import { collisionBoxesFor } from './types'
import type { AuthoredModule, ModuleAssembly } from './types'

/* ----------------------------------------------------------------- geometry */

/** Ops-module box [width, height, depth] m — the M0-T5 contract footprint. */
const WIDTH = 3.9
const DEPTH = 4.6
const HEIGHT = DECK_CLEAR_M
const HALF_X = WIDTH / 2
const HALF_Z = DEPTH / 2

/** Bulkhead thickness (kit default), m. */
const WALL_T = 0.1
/** Wall centre planes (flush with the module faces) and the room's inner faces. */
const WALL_CENTER_X = HALF_X - WALL_T / 2
const INNER_X = HALF_X - WALL_T
const INNER_Z = HALF_Z - WALL_T

/**
 * Rotation that reads "along the room": a bulkhead placed with yaw 1 has its
 * local +X running along module −Z (rotY turns (x, z) → (z, −x)), so a panel's
 * width and its `door.centerX` read directly as AFT-ward offsets. Both side
 * walls — and the airlock's starboard partition — are authored this way.
 */
const SIDE_WALL_ROTATION = 1 as const

/* ----------------------------------------------------------------- sockets */

/** The contract's side door: −x (port) face, standard centre, 1.0 m aft. */
const SIDE_DOOR_Z = -1.0
/** The same door's offset along the port panel's local +X (which maps to −Z). */
const SIDE_DOOR_PANEL_X = -SIDE_DOOR_Z

/* ----------------------------------------------------------------- airlock */

/**
 * The airlock vestibule, aft-port: closed off by a FORWARD partition (across
 * the room, carrying the 0.8 × 1.9 m interior doorway) and a STARBOARD
 * partition (running fore-and-aft). Its outer door is the port `side-door`.
 */
const AIRLOCK_PARTITION_X = -0.85
/** The starboard partition's room-side face — the tool wall's back. */
const AIRLOCK_INNER_X = AIRLOCK_PARTITION_X + WALL_T / 2
/** The vestibule centreline, for the suit rack and the airlock's own lamp. */
const AIRLOCK_CENTER_X = (-INNER_X + (AIRLOCK_PARTITION_X - WALL_T / 2)) / 2
/** Forward partition: spans x ∈ [−1.85, −0.85] at z = −0.4. */
const AIRLOCK_FWD_X = -1.35
const AIRLOCK_FWD_Z = -0.4
const AIRLOCK_FWD_WIDTH = 1.0
/** Starboard partition: spans z ∈ [−2.2, −0.45], x centred on −0.85. */
const AIRLOCK_SIDE_Z = -1.325
const AIRLOCK_SIDE_WIDTH = 1.75
/** The interior doorway in the forward partition (the airlock's inner hatch). */
const AIRLOCK_DOOR_WIDTH = 0.8
const AIRLOCK_DOOR_HEIGHT = 1.9
const AIRLOCK_DOOR_CENTER_Y = 0.95

/* --------------------------------------------------------------- suit rack */

/** The §4 "two vac suits on racks", on the vestibule's aft wall, facing in. */
const RACK_WIDTH = 0.9
const RACK_HEIGHT = 2.0
const RACK_DEPTH = 0.08
const RACK_X = AIRLOCK_CENTER_X
const RACK_Z = -INNER_Z + RACK_DEPTH / 2

/* --------------------------------------------------------------- tool wall */

/** Tool cabinets on the airlock partition's room face, doors into the room. */
const TOOL_WALL_WIDTH = 1.2
const TOOL_WALL_HEIGHT = 1.5
const TOOL_WALL_DEPTH = 0.3
const TOOL_WALL_X = AIRLOCK_INNER_X + TOOL_WALL_DEPTH / 2
const TOOL_WALL_Z = -1.4

/* ----------------------------------------------------------------- med bay */

/** Fold-down exam bed in the bow-starboard corner, head against the bow wall. */
const BED_X = 1.5
const BED_Z = 1.3
const BED_WIDTH = 0.7
const BED_LENGTH = 1.8
const BED_SURFACE_Y = 0.7
const BED_HEAD_Y = 0.4
/** Med cabinet on the forward wall, doors into the room (−z). */
const MED_CABINET_X = 0.75
const MED_CABINET_WIDTH = 0.7
const MED_CABINET_HEIGHT = 1.3
const MED_CABINET_DEPTH = 0.35
const MED_CABINET_Z = INNER_Z - MED_CABINET_DEPTH / 2
/** Med monitor on the starboard wall above the bed (yaw 3: faces −x). */
const MED_SCREEN_Y = 1.9
const MED_SCREEN_Z = 1.3

/* --------------------------------------------------------------- workbench */

/** Workbench along the starboard wall, its long axis fore-and-aft. */
const BENCH_X = 1.55
const BENCH_Z = -0.35
const BENCH_LENGTH = 1.4
const BENCH_DEPTH = 0.6
const BENCH_HEIGHT = 0.95
/** Bench terminal screen on the wall above it. */
const BENCH_SCREEN_Y = 1.85
const BENCH_SCREEN_Z = -0.5
/** Bench task strip light: recessed into the wall over the bench. */
const BENCH_TASK_X = INNER_X - 0.05
const BENCH_TASK_Y = 1.55
const BENCH_TASK_DEPTH = 0.25
/** Wall-mounted fixtures sit this far off the wall's inner face (half their depth). */
const SCREEN_MOUNT_X = INNER_X - 0.03
const SCREEN_DEPTH = 0.06

/* ------------------------------------------------------------------- lights */

/** Recessed panel lights just below the ceiling (housing top 0.03 m clear). */
const PANEL_Y = HEIGHT - 0.06
const AIRLOCK_PANEL_Z = -1.3
/** Exposed conduit runs: a ceiling main, a ceiling branch and two wall runs. */
const CONDUIT_RADIUS = 0.05
const CONDUIT_CLAMP_T = 0.03
const CEILING_MAIN_Y = 2.86
const CEILING_BRANCH_Y = 2.7
const WALL_RUN_Y = 2.5

/* ---------------------------------------------------------------- assemblies */

/** A recessed panel light at the kit's standard size. */
function panelLight(): ModuleAssembly['parts'] {
  return panelLightParts({
    width: 0.6,
    depth: 0.3,
    housingThickness: 0.06,
    lensInset: 0.08,
  })
}

/** A wall screen at the kit's standard size. */
function wallScreen(width = 0.7, height = 0.45): ModuleAssembly['parts'] {
  return screenParts({ width, height, depth: SCREEN_DEPTH, bezel: 0.03 })
}

/**
 * The ops module, assembly by assembly. Order is the build order: shell, the
 * two socket hatches, the airlock (partitions, inner hatch, rack, tool wall),
 * the workbench, the med bay, and finally the practical lighting + routing.
 */
export const OPS_ASSEMBLIES: readonly ModuleAssembly[] = [
  {
    id: 'deck-plate',
    parts: deckPlateParts({
      width: WIDTH,
      depth: DEPTH,
      thickness: 0.2,
      // Runs are laid clear of both doorway prisms (the aft spine breach at
      // z = −2.3 and the port side door at z = −1.0): ±1.6 m only.
      cableRuns: { count: 3, width: 0.12, height: 0.06, spacing: 1.6 },
    }),
    placement: { position: [0, 0, 0] },
    solid: true,
  },
  {
    id: 'wall-aft-spine',
    parts: bulkheadParts({
      width: WIDTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: { width: 0.9, height: 2.0, centerY: STANDARD_DOOR_CENTER_M },
    }),
    placement: { position: [0, 0, -(HALF_Z - WALL_T / 2)] },
    solid: true,
  },
  {
    id: 'wall-fwd',
    parts: bulkheadParts({ width: WIDTH, height: HEIGHT, thickness: WALL_T }),
    placement: { position: [0, 0, HALF_Z - WALL_T / 2] },
    solid: true,
  },
  {
    // Port wall, carrying the contract's off-centre `side-door` — the
    // airlock's outer door. Yaw 1 puts the panel's local +X along module −Z,
    // so the door's `centerX` IS the socket's aft-ward z offset.
    id: 'wall-port',
    parts: bulkheadParts({
      width: DEPTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: {
        width: 0.9,
        height: 2.0,
        centerY: STANDARD_DOOR_CENTER_M,
        centerX: SIDE_DOOR_PANEL_X,
      },
    }),
    placement: { position: [-WALL_CENTER_X, 0, 0], rotation: SIDE_WALL_ROTATION },
    solid: true,
  },
  {
    id: 'wall-stbd',
    parts: bulkheadParts({ width: DEPTH, height: HEIGHT, thickness: WALL_T }),
    placement: { position: [WALL_CENTER_X, 0, 0], rotation: SIDE_WALL_ROTATION },
    solid: true,
  },
  {
    // The room's hatch on its spine door (socket-centred: position = door
    // centre, local Z = wall normal). The spine module (M2-T6) brings the
    // shaft and its per-deck sockets — NOT a second hatch.
    id: 'hatch-spine',
    parts: hatchParts({
      door: { width: 0.9, height: 2.0 },
      leafThickness: 0.05,
      frameWidth: 0.05,
      clearance: 0.01,
    }),
    placement: { position: [0, STANDARD_DOOR_CENTER_M, -HALF_Z] },
    fillsSocket: true,
  },
  {
    // …and the room's hatch on the airlock's outer door, the same way.
    id: 'hatch-side',
    parts: hatchParts({
      door: { width: 0.9, height: 2.0 },
      leafThickness: 0.05,
      frameWidth: 0.05,
      clearance: 0.01,
    }),
    placement: {
      position: [-HALF_X, STANDARD_DOOR_CENTER_M, SIDE_DOOR_Z],
      rotation: SIDE_WALL_ROTATION,
    },
    fillsSocket: true,
  },
  {
    // Airlock forward partition: the vestibule's inner wall, with the 0.8 ×
    // 1.9 m interior doorway through it.
    id: 'partition-airlock-fwd',
    parts: bulkheadParts({
      width: AIRLOCK_FWD_WIDTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: {
        width: AIRLOCK_DOOR_WIDTH,
        height: AIRLOCK_DOOR_HEIGHT,
        centerY: AIRLOCK_DOOR_CENTER_Y,
      },
    }),
    placement: { position: [AIRLOCK_FWD_X, 0, AIRLOCK_FWD_Z] },
    solid: true,
  },
  {
    // Airlock starboard partition: runs fore-and-aft from the inner aft wall
    // corner forward to the forward partition — the vestibule's other wall.
    id: 'partition-airlock-stbd',
    parts: bulkheadParts({
      width: AIRLOCK_SIDE_WIDTH,
      height: HEIGHT,
      thickness: WALL_T,
    }),
    placement: {
      position: [AIRLOCK_PARTITION_X, 0, AIRLOCK_SIDE_Z],
      rotation: SIDE_WALL_ROTATION,
    },
    solid: true,
  },
  {
    // The airlock's interior hatch, seat ON the interior doorway (the same
    // socket-centred hatch the door sockets get). It fills an interior
    // opening rather than a DoorSocket, so it is not marked `fillsSocket`.
    id: 'hatch-airlock',
    parts: hatchParts({
      door: { width: AIRLOCK_DOOR_WIDTH, height: AIRLOCK_DOOR_HEIGHT },
      leafThickness: 0.05,
      frameWidth: 0.05,
      clearance: 0.01,
    }),
    placement: {
      position: [AIRLOCK_FWD_X, AIRLOCK_DOOR_CENTER_Y, AIRLOCK_FWD_Z],
    },
  },
  {
    // The §4 landmark: two vac suits on their rack, back flush on the
    // vestibule's aft wall, facing the interior hatch you enter through.
    id: 'suit-rack',
    parts: suitRackParts({
      width: RACK_WIDTH,
      height: RACK_HEIGHT,
      depth: RACK_DEPTH,
      suits: 2,
      suitWidth: 0.4,
      suitHeight: 0.85,
      suitDepth: 0.3,
      suitY: 0.7,
      helmetRadius: 0.15,
    }),
    placement: { position: [RACK_X, 0, RACK_Z] },
    solid: true,
  },
  {
    // The tool wall: a bank of tool cabinets on the airlock partition's room
    // face (yaw 1: the door face turns to +x, into the room).
    id: 'tool-wall',
    parts: lockerParts({
      width: TOOL_WALL_WIDTH,
      height: TOOL_WALL_HEIGHT,
      depth: TOOL_WALL_DEPTH,
      doors: 2,
      doorThickness: 0.03,
      doorGap: 0.02,
    }),
    placement: {
      position: [TOOL_WALL_X, 0, TOOL_WALL_Z],
      rotation: SIDE_WALL_ROTATION,
    },
    solid: true,
  },
  {
    // Workbench against the starboard wall, long axis fore-and-aft (yaw 1).
    id: 'workbench',
    parts: tableParts({
      width: BENCH_LENGTH,
      depth: BENCH_DEPTH,
      height: BENCH_HEIGHT,
      topThickness: 0.05,
      legRadius: 0.035,
    }),
    placement: { position: [BENCH_X, 0, BENCH_Z], rotation: SIDE_WALL_ROTATION },
    solid: true,
  },
  {
    // Bench terminal, on the wall above the bench (yaw 3: faces −x).
    id: 'bench-screen',
    parts: wallScreen(),
    placement: {
      position: [SCREEN_MOUNT_X, BENCH_SCREEN_Y, BENCH_SCREEN_Z],
      rotation: 3,
    },
  },
  {
    // The bench's own task strip light — the room's `task` fixture, recessed
    // into the wall over the bench surface.
    id: 'bench-task-light',
    parts: panelLightParts({
      width: 0.5,
      depth: BENCH_TASK_DEPTH,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: { position: [BENCH_TASK_X, BENCH_TASK_Y, BENCH_Z], rotation: 3 },
  },
  {
    // The med bay's exam bed: the couch primitive read as a bed — no straps,
    // headboard forward (yaw 2), against the bow and starboard walls.
    id: 'exam-bed',
    parts: couchParts({
      width: BED_WIDTH,
      depth: BED_LENGTH,
      seatHeight: BED_SURFACE_Y,
      backHeight: BED_HEAD_Y,
      straps: 0,
    }),
    placement: { position: [BED_X, 0, BED_Z], rotation: 2 },
    solid: true,
  },
  {
    // Med cabinet on the forward wall above the foot of the bed (yaw 2: its
    // door face turns to −z, into the room).
    id: 'med-cabinet',
    parts: lockerParts({
      width: MED_CABINET_WIDTH,
      height: MED_CABINET_HEIGHT,
      depth: MED_CABINET_DEPTH,
      doors: 1,
      doorThickness: 0.03,
      doorGap: 0.02,
    }),
    placement: { position: [MED_CABINET_X, 0, MED_CABINET_Z], rotation: 2 },
    solid: true,
  },
  {
    // Med monitor over the bed — the med bay's `screen` light source.
    id: 'med-screen',
    parts: wallScreen(0.6, 0.45),
    placement: { position: [SCREEN_MOUNT_X, MED_SCREEN_Y, MED_SCREEN_Z], rotation: 3 },
  },
  {
    id: 'panel-light-airlock',
    parts: panelLight(),
    placement: { position: [AIRLOCK_CENTER_X, PANEL_Y, AIRLOCK_PANEL_Z] },
  },
  {
    id: 'panel-light-aft',
    parts: panelLight(),
    placement: { position: [0.6, PANEL_Y, -1.6] },
  },
  {
    id: 'panel-light-med',
    parts: panelLight(),
    placement: { position: [0.9, PANEL_Y, 1.2] },
  },
  {
    id: 'panel-light-bench',
    parts: panelLight(),
    placement: { position: [1.6, PANEL_Y, BENCH_Z] },
  },
  {
    id: 'conduit-ceiling-main',
    parts: conduitRunParts({
      length: WIDTH - 0.4,
      radius: CONDUIT_RADIUS,
      axis: 'x',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [0, CEILING_MAIN_Y, -1.3] },
  },
  {
    id: 'conduit-ceiling-branch',
    parts: conduitRunParts({
      length: 2.4,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [1.2, CEILING_BRANCH_Y, 0.6] },
  },
  {
    id: 'conduit-stbd',
    parts: conduitRunParts({
      length: 2.4,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [INNER_X - CONDUIT_RADIUS, WALL_RUN_Y, BENCH_Z] },
  },
  {
    // Port wall run, bow-ward of the airlock's outer door it would otherwise
    // cross (the door spans z ∈ [−1.45, −0.55]).
    id: 'conduit-port',
    parts: conduitRunParts({
      length: 1.6,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 3,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [-INNER_X + CONDUIT_RADIUS, WALL_RUN_Y, 1.4] },
  },
]

/* ------------------------------------------------------------------- anchors */

/** An assembly's module-local placement (throws on a typo'd assembly id). */
function placementOf(assemblyId: string) {
  const assembly = OPS_ASSEMBLIES.find((candidate) => candidate.id === assemblyId)
  if (assembly === undefined) {
    throw new Error(`ops module: no assembly "${assemblyId}"`)
  }
  return assembly.placement
}

/**
 * An equipment anchor AT the assembly's own origin — anchors and geometry
 * share one source, so a moved prop moves its anchor with it.
 */
function equipmentSlot(assemblyId: string): EquipmentSlot {
  const { position, rotation } = placementOf(assemblyId)
  return { id: assemblyId, position: position ?? [0, 0, 0], rotation: rotation ?? 0 }
}

/** A light fixture anchor at an assembly's origin (panel lights, displays). */
function lightSocketOf(assemblyId: string, kind: LightKind): LightSocket {
  const { position, rotation } = placementOf(assemblyId)
  return {
    id: assemblyId,
    kind,
    position: position ?? [0, 0, 0],
    rotation: rotation ?? 0,
  }
}

/** The lens offset inside a panel-light primitive (panelLightParts), meters. */
const PANEL_LENS_LOCAL: Vec3 = [0, -0.03, 0]

/**
 * The workbench's task-light anchor, read off the fixture's OWN emissive part:
 * `panelLightParts` puts the lens 0.03 m below the housing centre, so the
 * socket is that primitive-local point placed through the same transform the
 * parts went through (placePoint) — the M4-T1 rig lights the real lens.
 */
function benchTaskLight(): LightSocket {
  return {
    id: 'bench-task-light',
    kind: 'task',
    position: placePoint(PANEL_LENS_LOCAL, placementOf('bench-task-light')),
  }
}

/* ------------------------------------------------------------------- module */

/**
 * The authored ops module: the M1-T2 manifest entry (contract dims, the
 * standardized spine door + the contract side door, the §4 landmark anchors,
 * the derived collision hint) plus the assemblies that build it.
 */
export const OPS_MODULE: AuthoredModule = {
  manifest: {
    id: 'ops',
    label: 'Ops (airlock + suit locker, workbench, med bay)',
    dimensions: [WIDTH, HEIGHT, DEPTH],
    doorSockets: [
      // The standardized spine door: −z face, flush, standard 1.0 m centre —
      // exactly the contract origin (src/validation/contractKit.ts).
      {
        id: 'spine-door',
        position: [0, STANDARD_DOOR_CENTER_M, -HALF_Z],
        facing: '-z',
      },
      // The contract's side door — the airlock's outer door: −x face,
      // standard centre, 1.0 m aft along the wall.
      {
        id: 'side-door',
        position: [-HALF_X, STANDARD_DOOR_CENTER_M, SIDE_DOOR_Z],
        facing: '-x',
      },
    ],
    lightSockets: [
      lightSocketOf('panel-light-airlock', 'panel'),
      lightSocketOf('panel-light-aft', 'panel'),
      lightSocketOf('panel-light-med', 'panel'),
      lightSocketOf('panel-light-bench', 'panel'),
      benchTaskLight(),
      lightSocketOf('bench-screen', 'screen'),
      lightSocketOf('med-screen', 'screen'),
    ],
    equipmentSlots: [
      equipmentSlot('hatch-spine'),
      equipmentSlot('hatch-side'),
      equipmentSlot('hatch-airlock'),
      equipmentSlot('suit-rack'),
      equipmentSlot('tool-wall'),
      equipmentSlot('workbench'),
      equipmentSlot('bench-screen'),
      equipmentSlot('bench-task-light'),
      equipmentSlot('exam-bed'),
      equipmentSlot('med-cabinet'),
      equipmentSlot('med-screen'),
    ],
    collisionHint: { boxes: collisionBoxesFor(OPS_ASSEMBLIES) },
  },
  assemblies: OPS_ASSEMBLIES,
}
