/**
 * M2-T6 — the authored SPINE module: the vertical ladder / crawl shaft.
 *
 * PRD §4 landmark: "The spine: the ladder/crawl shaft connecting all decks —
 * the ship's vertical artery." The spine is a kit module type like any other
 * (src/types/kit.ts), but the assembler instantiates it once per deck instead
 * of from a spec ref (src/types/ship.ts: "the spine shaft is NOT referenced —
 * the assembler synthesizes one spine band per deck"). So this module IS ONE
 * BAND: one deck's worth of trunk, stacked floor-to-floor into the continuous
 * vertical run.
 *
 * Why one band and not one tall shaft module: a module type has fixed
 * `dimensions`, and ships carry 5, 6 or more decks. A band of one deck pitch
 * tiles any deck count, and `dimensions[1] === DECK_PITCH_M` is exactly the
 * statement that consecutive bands stack with no gap and no overlap
 * (deckFloorYFor(i+1) + pitch === deckFloorYFor(i)).
 *
 * The band, in the M1-T2 authoring frame (floor at local y = 0, footprint
 * centred on the origin in XZ):
 *
 *  - the shaft is a 1.4 m square trunk (SPINE_SHAFT_HALF_M = 0.7 — the M0-T2
 *    white-box band and the fixture layout's canonical spine column);
 *  - FOUR face doorways, ids '+z' / '−z' / '+x' / '−x', one per face, each
 *    flush in its face at the standard 1.0 m centre with the standard
 *    0.9 × 2.0 m opening. These are exactly the sockets the M1-T3 validator
 *    synthesizes per deck (`spineBandDoors`, src/validation/sockets.ts) — the
 *    table every deck's rooms land their own `spine-door` on, and the table
 *    spine.test.ts diffs this module against;
 *  - each face's wall is CUT by the kit bulkhead builder at its own socket
 *    (rule 8: mating geometry comes from sockets, never freehand), so a room
 *    joins the shaft through an opening guaranteed to line up;
 *  - the deck plate is a closed frame around a 0.7 × 0.7 CRAWL OPENING on the
 *    shaft axis — the hole the ladder run passes through to reach the deck
 *    above. The band's plate is the ceiling of the band below, which is why
 *    the opening lives here and not in the band the ladder starts from;
 *  - the LADDER is one full deck PITCH tall (rails 0 → 3.2 m, ten rungs on a
 *    0.3 m pitch from 0.3 to 3.0), so the rungs line up across the deck
 *    boundary: last rung of a storey (3.0) → deck above's floor (3.2) → its
 *    first rung (3.5). It is the only geometry in the band's top 0.2 m, which
 *    is why the band's declared box is a full pitch tall rather than one deck
 *    clear height (3.0): the run's top rail lands ON the deck above's floor;
 *  - practical lighting: two recessed panel lights, above the doorway heads;
 *  - two vertical cable trees (exposed service routing) in opposite corners —
 *    the only free volume outside the four doorway prisms and the ladder.
 *
 * The ROOM owns the hatch on its own spine-door socket (M2-T2 cross-task
 * seam): the spine brings the shaft, the four doorways and the ladder, and
 * must NOT author a second hatch — nothing here is `fillsSocket`. A face with
 * no room on it is an unjoined socket, which the M1-T3 validator legalizes as
 * blanked; the M3-T2 assembler generates the blanking sleeve from the socket.
 *
 * Everything is generated by the M2-T1 builders and placed through the
 * placement layer; `SPINE_ASSEMBLIES` is the authored truth, and the
 * manifest's collision hint is derived from it (`collisionBoxesFor`), so the
 * M3-T3 hull can never drift from the geometry the walkthrough renders.
 */

import {
  DECK_CLEAR_M,
  DECK_PITCH_M,
  STANDARD_DOOR_CENTER_M,
  doorSizeOf,
} from '../../types'
import type {
  DoorSocket,
  EquipmentSlot,
  Facing,
  LightKind,
  LightSocket,
  Vec3,
} from '../../types'
import type { PrimitivePlacement } from '../types'
import {
  bulkheadParts,
  conduitRunParts,
  deckPlateParts,
  ladderSegmentParts,
  panelLightParts,
} from '../parts'
import { SHAFT_FACES, collisionBoxesFor } from './types'
import type { AuthoredModule, ModuleAssembly } from './types'

/* ----------------------------------------------------------------- geometry */

/** Shaft outer half-extent in XZ, meters (1.4 m square trunk). */
export const SPINE_SHAFT_HALF_M = 0.7
const WIDTH = SPINE_SHAFT_HALF_M * 2
const DEPTH = SPINE_SHAFT_HALF_M * 2

/** Deck clear height (band floor → the deck plate above), meters. */
const CLEAR = DECK_CLEAR_M
/** The band's declared height: one full deck pitch, floor to floor. */
const HEIGHT = DECK_PITCH_M

/** Bulkhead thickness (kit default), m, and the wall centre plane. */
const WALL_T = 0.1
const WALL_CENTER = SPINE_SHAFT_HALF_M - WALL_T / 2

/** Deck-plate thickness, m (the 0.2 m of the deck pitch). */
const PLATE_T = 0.2

/**
 * The crawl opening in the band's deck plate, meters: the ladder's passage to
 * the deck above (and the band below's ladder into this deck). 0.7 m square on
 * the shaft axis — wide enough to climb through, small enough to leave a
 * 0.35 m plate frame all round, and clear of every doorway prism.
 */
export const SPINE_CRAWL_OPENING = { width: 0.7, depth: 0.7 } as const

/** The ladder run: rails reach the deck above's floor, rungs on a 0.3 m pitch. */
export const SPINE_LADDER_PARAMS = {
  height: DECK_PITCH_M,
  width: 0.45,
  railRadius: 0.03,
  rungRadius: 0.018,
  rungSpacing: 0.3,
  firstRungY: 0.3,
} as const

/** Recessed panel lights: one per side of the trunk, just below the ceiling. */
const PANEL_Y = CLEAR - 0.06
const PANEL_Z = 0.38

/** Vertical cable trees: in the two free diagonal corners, hugging the walls. */
const TREE_RADIUS = 0.03
const TREE_AT = 0.525
const TREE_BRACKETS = 3

/* ---------------------------------------------------------------- doorways */

/**
 * Where each band doorway sits: flush in its own face, at the standard 1.0 m
 * door centre. The four-pose table IS the band contract the rooms land on
 * (src/validation/sockets.ts `spineBandDoors`).
 */
const FACE_SOCKET_POSITION: Record<Facing, Vec3> = {
  '+z': [0, STANDARD_DOOR_CENTER_M, SPINE_SHAFT_HALF_M],
  '-z': [0, STANDARD_DOOR_CENTER_M, -SPINE_SHAFT_HALF_M],
  '+x': [SPINE_SHAFT_HALF_M, STANDARD_DOOR_CENTER_M, 0],
  '-x': [-SPINE_SHAFT_HALF_M, STANDARD_DOOR_CENTER_M, 0],
}

/**
 * The four band doorways, one per face: socket id = the face it opens through,
 * opening = the standard 0.9 × 2.0 m (omitted `door`), centre = the standard
 * 1.0 m. Ids match the validator's synthesized band sockets exactly, so a room
 * landing on the shaft and the shaft it lands on speak one socket vocabulary.
 */
const BAND_DOOR_SOCKETS: DoorSocket[] = SHAFT_FACES.map((facing) => ({
  id: facing,
  position: FACE_SOCKET_POSITION[facing],
  facing,
}))

/** Panel width a face wall spans: the shaft's extent across that face, m. */
function faceSpan(facing: Facing): number {
  return facing === '+x' || facing === '-x' ? DEPTH : WIDTH
}

/**
 * Where a face wall sits: flush inside the shaft's outer face, rotated so its
 * panel normal (local ±Z) points out through that face. Local +X of a ±X wall
 * maps to world ∓Z (rotY), which keeps the doorway cut centred on the socket.
 */
function wallPlacement(facing: Facing): PrimitivePlacement {
  switch (facing) {
    case '+z':
      return { position: [0, 0, WALL_CENTER] }
    case '-z':
      return { position: [0, 0, -WALL_CENTER] }
    case '+x':
      return { position: [WALL_CENTER, 0, 0], rotation: 1 }
    case '-x':
      return { position: [-WALL_CENTER, 0, 0], rotation: 1 }
  }
}

/**
 * One face wall, CUT at its own socket: the opening's width, height and centre
 * come from the DoorSocket declaration, so the hole in the wall and the socket
 * the assembler joins on cannot drift apart (rule 8). The panel reaches the
 * deck plate above (y = CLEAR) — the band's headroom.
 */
function faceWall(socket: DoorSocket): ModuleAssembly {
  const door = doorSizeOf(socket)
  return {
    id: `wall-${socket.id}`,
    parts: bulkheadParts({
      width: faceSpan(socket.facing),
      height: CLEAR,
      thickness: WALL_T,
      door: {
        width: door.width,
        height: door.height,
        centerY: socket.position[1],
      },
    }),
    placement: wallPlacement(socket.facing),
    solid: true,
  }
}

/* ---------------------------------------------------------------- assemblies */

/**
 * The band, assembly by assembly, in build order: the shaft floor with its
 * crawl opening, the four face walls (cut at their sockets), the ladder run,
 * the cable trees, then the practical lighting.
 */
export const SPINE_ASSEMBLIES: readonly ModuleAssembly[] = [
  {
    id: 'deck-plate',
    parts: deckPlateParts({
      width: WIDTH,
      depth: DEPTH,
      thickness: PLATE_T,
      opening: { ...SPINE_CRAWL_OPENING },
    }),
    placement: { position: [0, 0, 0] },
    solid: true,
  },
  ...BAND_DOOR_SOCKETS.map(faceWall),
  {
    // The vertical run: rails floor → deck above's floor, rungs on a constant
    // 0.3 m pitch so the climb is continuous across the deck boundary.
    id: 'ladder',
    parts: ladderSegmentParts({ ...SPINE_LADDER_PARAMS }),
    placement: { position: [0, 0, 0] },
    solid: true,
  },
  {
    id: 'cable-tree-stbd-fwd',
    parts: conduitRunParts({
      length: CLEAR,
      radius: TREE_RADIUS,
      axis: 'y',
      brackets: TREE_BRACKETS,
      clampThickness: 0.03,
    }),
    placement: { position: [TREE_AT, CLEAR / 2, TREE_AT] },
  },
  {
    id: 'cable-tree-port-aft',
    parts: conduitRunParts({
      length: CLEAR,
      radius: TREE_RADIUS,
      axis: 'y',
      brackets: TREE_BRACKETS,
      clampThickness: 0.03,
    }),
    placement: { position: [-TREE_AT, CLEAR / 2, -TREE_AT] },
  },
  {
    id: 'panel-light-fwd',
    parts: panelLightParts({
      width: 0.6,
      depth: 0.3,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: { position: [0, PANEL_Y, PANEL_Z] },
  },
  {
    id: 'panel-light-aft',
    parts: panelLightParts({
      width: 0.6,
      depth: 0.3,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: { position: [0, PANEL_Y, -PANEL_Z] },
  },
]

/* ------------------------------------------------------------------- anchors */

/** An assembly's module-local placement (throws on a typo'd assembly id). */
function placementOf(assemblyId: string): PrimitivePlacement {
  const assembly = SPINE_ASSEMBLIES.find((candidate) => candidate.id === assemblyId)
  if (assembly === undefined) {
    throw new Error(`spine module: no assembly "${assemblyId}"`)
  }
  return assembly.placement
}

/**
 * An equipment anchor AT the assembly's own origin — anchors and geometry
 * share one source, so a moved fixture moves its anchor with it.
 */
function equipmentSlot(assemblyId: string): EquipmentSlot {
  const { position, rotation } = placementOf(assemblyId)
  return { id: assemblyId, position: position ?? [0, 0, 0], rotation: rotation ?? 0 }
}

/** A light fixture anchor at an assembly's origin (the panel lights). */
function lightSocketOf(assemblyId: string, kind: LightKind): LightSocket {
  const { position, rotation } = placementOf(assemblyId)
  return {
    id: assemblyId,
    kind,
    position: position ?? [0, 0, 0],
    rotation: rotation ?? 0,
  }
}

/* ------------------------------------------------------------------- module */

/**
 * The authored spine band: the M1-T2 manifest entry (contract dims, the four
 * face doorways, the vertical-navigation anchors, the derived collision hint)
 * plus the assemblies that build it. `shaft: true` marks it for the assembler
 * and enables the shaft doorway rules in integrity.ts.
 */
export const SPINE_MODULE: AuthoredModule = {
  shaft: true,
  manifest: {
    id: 'spine',
    label: 'Spine shaft (vertical ladder / crawl trunk, per-deck door sockets)',
    dimensions: [WIDTH, HEIGHT, DEPTH],
    doorSockets: BAND_DOOR_SOCKETS,
    lightSockets: [
      lightSocketOf('panel-light-fwd', 'panel'),
      lightSocketOf('panel-light-aft', 'panel'),
    ],
    equipmentSlots: [
      equipmentSlot('ladder'),
      equipmentSlot('deck-plate'),
      equipmentSlot('cable-tree-stbd-fwd'),
      equipmentSlot('cable-tree-port-aft'),
    ],
    collisionHint: { boxes: collisionBoxesFor(SPINE_ASSEMBLIES) },
  },
  assemblies: SPINE_ASSEMBLIES,
}

/**
 * The ladder's rung heights above the band's floor, in climb order — read off
 * the geometry (the M2-T1 ladder builder derives the rung count from the
 * spacing), so the M3-T5 climb state machine climbs the rungs that are really
 * there instead of re-deriving them.
 */
export function spineRungHeights(): number[] {
  const ladder = SPINE_ASSEMBLIES.find((assembly) => assembly.id === 'ladder')
  if (ladder === undefined) return []
  return ladder.parts
    .filter((part) => part.kind === 'cylinder' && part.axis === 'x')
    .map((part) => part.position[1])
}
