/**
 * M2-T5 — the authored STORAGE module: the long-haul cargo hold.
 *
 * BUILD_PLAN M2-T5: "…+ storage module (long-haul variant)". The long-haul
 * preset (src/fixtures/longHaul.ts) stretches the corvette with a SECOND aft
 * cargo deck, so this room is the module the stretch is made of: a bare,
 * unglamorous hold that still has to be a place — cargo lashed down, a spares
 * rack, and a loadmaster's station where the manifest is kept.
 *
 * The room is one deck module on the M1-T2 authoring frame — floor at local
 * y = 0, footprint centred on the origin in XZ, the standardized `spine-door`
 * flush in the module's −z face at the standard 1.0 m centre (src/fixtures/
 * layout.ts). It is the deepest room of the kit (6.0 m), which is what makes it
 * read as a hold rather than a cabin.
 *
 * Reading the room from the spine door (aft, −z) toward the bow (+z):
 *  - CARGO CRATES stack two high in four lashed-down stacks — two along the
 *    port wall (aft and amidships) and two along the starboard wall (aft and
 *    forward of the side door) — each crate on its own skids with webbing
 *    tie-downs over the lid and down both ends, so the load reads as secured;
 *  - the centreline stays clear from the spine door to the bow wall: the
 *    walkway, not a crawl, because the hold is where the crew moves freight;
 *  - the SPARES RACK (a two-door locker bank) lines the port wall forward,
 *    opposite the loadmaster's station;
 *  - the LOADMASTER'S STATION fills the bow-starboard corner: a bench with a
 *    terminal display on the bow wall and its own task strip light above it;
 *  - the rest is practical lighting (four ceiling panels) and exposed conduit
 *    routing down the hold.
 *
 * The starboard wall carries the contract's `side-door` socket (M1-T3
 * contractKit) — off-centre along the wall and facing +x — so the wall panel is
 * cut with the bulkhead builder's `door.centerX` (never freehand geometry,
 * BUILD_PLAN rule 8) and the opening is sealed with a socket-centred hatch, the
 * same way the spine door is. Both hatches belong to the room; the M2-T6 spine
 * module supplies the shaft + per-deck sockets and adds NO hatch of its own.
 *
 * Everything is generated by the M2-T1 builders and placed through `placePart`
 * / `placePoint`; `STORAGE_ASSEMBLIES` is the authored truth, and the anchors
 * (light sockets, equipment slots) are DERIVED from those placements so they
 * can never drift from the geometry. The manifest's collision hint is derived
 * the same way (`collisionBoxesFor`).
 */

import { DECK_CLEAR_M, STANDARD_DOOR_CENTER_M } from '../../types'
import type { EquipmentSlot, LightKind, LightSocket, Vec3 } from '../../types'
import {
  bulkheadParts,
  cargoCrateParts,
  conduitRunParts,
  deckPlateParts,
  hatchParts,
  lockerParts,
  panelLightParts,
  screenParts,
  tableParts,
} from '../parts'
import { placePoint } from './placement'
import { collisionBoxesFor } from './types'
import type { AuthoredModule, ModuleAssembly } from './types'

/* ----------------------------------------------------------------- geometry */

/** Storage-module box [width, height, depth] m — the M0-T5 contract footprint. */
const WIDTH = 4.0
const DEPTH = 6.0
const HEIGHT = DECK_CLEAR_M
const HALF_X = WIDTH / 2
const HALF_Z = DEPTH / 2

/** Bulkhead thickness (kit default), m. */
const WALL_T = 0.1
/** Wall centre planes (flush with the module faces) and the room's inner faces. */
const WALL_CENTER_X = HALF_X - WALL_T / 2
const INNER_X = HALF_X - WALL_T
const INNER_Z = HALF_Z - WALL_T

/** Rotation that reads "along the room": yaw 1 runs the panel's local +X along module −Z. */
const PORT_WALL_ROTATION = 1 as const
/** Yaw 3 runs the panel's local +X along module +Z — how the starboard wall is authored. */
const STBD_WALL_ROTATION = 3 as const

/* ------------------------------------------------------------------ sockets */

/** The contract's side door: +x (starboard) face, standard centre, 1.0 m bow-ward. */
const SIDE_DOOR_Z = 1.0

/* -------------------------------------------------------------------- cargo */

/**
 * The kit's cargo crate (M2-T5 primitive), at the hold's standard size: a
 * 0.9 × 0.7 × 1.2 m container on 0.06 m skids, lashed by two webbing straps —
 * 0.78 m tall on the deck, which is what the stacks are pitched at.
 */
function crate(): ModuleAssembly['parts'] {
  return cargoCrateParts({
    width: 0.9,
    height: 0.7,
    depth: 1.2,
    skidHeight: 0.06,
    skidThickness: 0.08,
    straps: 2,
    strapWidth: 0.06,
    strapThickness: 0.02,
  })
}

/** Lid-to-skid height of one crate including its tie-down straps, m. */
const CRATE_PITCH = 0.78
/** Crate centres: x flush on the wall, z along the hold, long axis fore-and-aft. */
const CRATE_PORT_X = -1.45
const CRATE_STBD_X = 1.45
/** The forward starboard stack sits inboard, clear of the side-door sweep. */
const CRATE_STBD_FWD_X = 1.35
const CRATE_PORT_AFT_Z = -1.9
const CRATE_PORT_MID_Z = 0.0
const CRATE_STBD_AFT_Z = -2.0
const CRATE_STBD_FWD_Z = 1.6

/* -------------------------------------------------------------------- spares */

/** Two-door spares rack on the port wall forward (yaw 1: doors into the room). */
const SPARES_RACK_X = -INNER_X + 0.25
const SPARES_RACK_Z = 1.7
const SPARES_RACK_WIDTH = 1.6
const SPARES_RACK_HEIGHT = 2.2
const SPARES_RACK_DEPTH = 0.5

/* ---------------------------------------------------------- loadmaster station */

/** The loadmaster's bench on the bow wall, terminal above it. */
const BENCH_X = 1.2
const BENCH_Z = INNER_Z - 0.35
const BENCH_WIDTH = 1.0
const BENCH_DEPTH = 0.6
const BENCH_HEIGHT = 0.9
const LOADMASTER_SCREEN_Y = 2.0
const LOADMASTER_TASK_Y = 1.5
/** Wall-mounted fixtures sit this far off the wall's inner face. */
const SCREEN_MOUNT_Z = INNER_Z - 0.03
const SCREEN_DEPTH = 0.06
const TASK_STRIP_DEPTH = 0.25

/* ------------------------------------------------------------------- lights */

/** Recessed panel lights just below the ceiling (housing top 0.03 m clear). */
const PANEL_Y = HEIGHT - 0.06
/** Exposed conduit runs: a ceiling main, a ceiling branch and two wall runs. */
const CONDUIT_RADIUS = 0.05
const CONDUIT_CLAMP_T = 0.03
const CEILING_MAIN_Y = 2.86
const CEILING_BRANCH_Y = 2.7
const WALL_RUN_Y = 2.5

/* ---------------------------------------------------------------- assemblies */

/** A recessed panel light at the kit's standard size. */
function panelLight(): ModuleAssembly['parts'] {
  return panelLightParts({
    width: 0.6,
    depth: 0.3,
    housingThickness: 0.06,
    lensInset: 0.08,
  })
}

/** A named stack: one crate on the deck, its twin lashed on top of it. */
function crateStack(id: string, x: number, z: number): ModuleAssembly[] {
  return [
    {
      id: `${id}-lower`,
      parts: crate(),
      placement: { position: [x, 0, z] },
      solid: true,
    },
    {
      id: `${id}-upper`,
      parts: crate(),
      placement: { position: [x, CRATE_PITCH, z] },
      solid: true,
    },
  ]
}

/**
 * The storage / cargo hold, assembly by assembly. Order is the build order:
 * shell, the two socket hatches, the four lashed cargo stacks, the spares rack,
 * the loadmaster's station, and finally the practical lighting + routing.
 */
export const STORAGE_ASSEMBLIES: readonly ModuleAssembly[] = [
  {
    id: 'deck-plate',
    parts: deckPlateParts({
      width: WIDTH,
      depth: DEPTH,
      thickness: 0.2,
      // Runs are laid clear of both doorway prisms (the aft spine breach at
      // z = −3.0 and the starboard side door at z = 1.0): ±2.2 m only.
      cableRuns: { count: 3, width: 0.12, height: 0.06, spacing: 2.2 },
    }),
    placement: { position: [0, 0, 0] },
    solid: true,
  },
  {
    id: 'wall-aft-spine',
    parts: bulkheadParts({
      width: WIDTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: { width: 0.9, height: 2.0, centerY: STANDARD_DOOR_CENTER_M },
    }),
    placement: { position: [0, 0, -(HALF_Z - WALL_T / 2)] },
    solid: true,
  },
  {
    id: 'wall-fwd',
    parts: bulkheadParts({ width: WIDTH, height: HEIGHT, thickness: WALL_T }),
    placement: { position: [0, 0, HALF_Z - WALL_T / 2] },
    solid: true,
  },
  {
    id: 'wall-port',
    parts: bulkheadParts({ width: DEPTH, height: HEIGHT, thickness: WALL_T }),
    placement: { position: [-WALL_CENTER_X, 0, 0], rotation: PORT_WALL_ROTATION },
    solid: true,
  },
  {
    // Starboard wall, carrying the contract's off-centre `side-door` opening:
    // yaw 3 puts the panel's local +X along module +Z, so the door's
    // `centerX` IS the socket's bow-ward z offset.
    id: 'wall-stbd',
    parts: bulkheadParts({
      width: DEPTH,
      height: HEIGHT,
      thickness: WALL_T,
      door: {
        width: 0.9,
        height: 2.0,
        centerY: STANDARD_DOOR_CENTER_M,
        centerX: SIDE_DOOR_Z,
      },
    }),
    placement: { position: [WALL_CENTER_X, 0, 0], rotation: STBD_WALL_ROTATION },
    solid: true,
  },
  {
    // The room's hatch on its spine door (socket-centred: position = door
    // centre, local Z = wall normal). The spine module (M2-T6) brings the
    // shaft and its per-deck sockets — NOT a second hatch.
    id: 'hatch-spine',
    parts: hatchParts({
      door: { width: 0.9, height: 2.0 },
      leafThickness: 0.05,
      frameWidth: 0.05,
      clearance: 0.01,
    }),
    placement: { position: [0, STANDARD_DOOR_CENTER_M, -HALF_Z] },
    fillsSocket: true,
  },
  {
    // …and the room's hatch on the side door, the same way.
    id: 'hatch-side',
    parts: hatchParts({
      door: { width: 0.9, height: 2.0 },
      leafThickness: 0.05,
      frameWidth: 0.05,
      clearance: 0.01,
    }),
    placement: {
      position: [HALF_X, STANDARD_DOOR_CENTER_M, SIDE_DOOR_Z],
      rotation: STBD_WALL_ROTATION,
    },
    fillsSocket: true,
  },
  ...crateStack('crate-port-aft', CRATE_PORT_X, CRATE_PORT_AFT_Z),
  ...crateStack('crate-port-mid', CRATE_PORT_X, CRATE_PORT_MID_Z),
  ...crateStack('crate-stbd-aft', CRATE_STBD_X, CRATE_STBD_AFT_Z),
  ...crateStack('crate-stbd-fwd', CRATE_STBD_FWD_X, CRATE_STBD_FWD_Z),
  {
    // Spares rack against the port wall forward (doors proud into the room).
    id: 'spares-rack',
    parts: lockerParts({
      width: SPARES_RACK_WIDTH,
      height: SPARES_RACK_HEIGHT,
      depth: SPARES_RACK_DEPTH,
      doors: 2,
      doorThickness: 0.03,
      doorGap: 0.02,
    }),
    placement: {
      position: [SPARES_RACK_X, 0, SPARES_RACK_Z],
      rotation: PORT_WALL_ROTATION,
    },
    solid: true,
  },
  {
    // The loadmaster's bench, on the bow wall (long axis across the room).
    id: 'loadmaster-bench',
    parts: tableParts({
      width: BENCH_WIDTH,
      depth: BENCH_DEPTH,
      height: BENCH_HEIGHT,
      topThickness: 0.05,
      legRadius: 0.03,
    }),
    placement: { position: [BENCH_X, 0, BENCH_Z] },
    solid: true,
  },
  {
    // The loadmaster's terminal on the bow wall above the bench (yaw 2: faces −z).
    id: 'loadmaster-screen',
    parts: screenParts({ width: 0.6, height: 0.45, depth: SCREEN_DEPTH, bezel: 0.03 }),
    placement: {
      position: [BENCH_X, LOADMASTER_SCREEN_Y, SCREEN_MOUNT_Z],
      rotation: 2,
    },
  },
  {
    // The bench's own task strip light — the room's `task` fixture, recessed
    // into the bow wall over the bench surface.
    id: 'loadmaster-task-light',
    parts: panelLightParts({
      width: 0.5,
      depth: TASK_STRIP_DEPTH,
      housingThickness: 0.06,
      lensInset: 0.08,
    }),
    placement: {
      position: [BENCH_X, LOADMASTER_TASK_Y, INNER_Z - 0.05],
      rotation: 2,
    },
  },
  {
    id: 'panel-light-aft',
    parts: panelLight(),
    placement: { position: [-0.6, PANEL_Y, -2.2] },
  },
  {
    id: 'panel-light-mid-aft',
    parts: panelLight(),
    placement: { position: [0.6, PANEL_Y, -0.8] },
  },
  {
    id: 'panel-light-mid-fwd',
    parts: panelLight(),
    placement: { position: [-0.6, PANEL_Y, 0.6] },
  },
  {
    id: 'panel-light-fwd',
    parts: panelLight(),
    placement: { position: [0.6, PANEL_Y, 2.0] },
  },
  {
    id: 'conduit-ceiling-main',
    parts: conduitRunParts({
      length: WIDTH - 0.4,
      radius: CONDUIT_RADIUS,
      axis: 'x',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [0, CEILING_MAIN_Y, -2.4] },
  },
  {
    id: 'conduit-ceiling-branch',
    parts: conduitRunParts({
      length: 5.2,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 6,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [-1.0, CEILING_BRANCH_Y, 0.2] },
  },
  {
    // Port wall run, the length of the hold (over the cargo rows).
    id: 'conduit-port',
    parts: conduitRunParts({
      length: 5.4,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 6,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [-INNER_X + CONDUIT_RADIUS, WALL_RUN_Y, 0] },
  },
  {
    // Starboard wall run, stopped short of the side-door opening (z = 0.55).
    id: 'conduit-stbd',
    parts: conduitRunParts({
      length: 3.6,
      radius: CONDUIT_RADIUS,
      axis: 'z',
      brackets: 4,
      clampThickness: CONDUIT_CLAMP_T,
    }),
    placement: { position: [INNER_X - CONDUIT_RADIUS, WALL_RUN_Y, -1.0] },
  },
]

/* ------------------------------------------------------------------- anchors */

/** An assembly's module-local placement (throws on a typo'd assembly id). */
function placementOf(assemblyId: string) {
  const assembly = STORAGE_ASSEMBLIES.find((candidate) => candidate.id === assemblyId)
  if (assembly === undefined) {
    throw new Error(`storage module: no assembly "${assemblyId}"`)
  }
  return assembly.placement
}

/**
 * An equipment anchor AT the assembly's own origin — anchors and geometry
 * share one source, so a moved crate moves its anchor with it.
 */
function equipmentSlot(assemblyId: string): EquipmentSlot {
  const { position, rotation } = placementOf(assemblyId)
  return { id: assemblyId, position: position ?? [0, 0, 0], rotation: rotation ?? 0 }
}

/** A light fixture anchor at an assembly's origin (panel lights, displays). */
function lightSocketOf(assemblyId: string, kind: LightKind): LightSocket {
  const { position, rotation } = placementOf(assemblyId)
  return {
    id: assemblyId,
    kind,
    position: position ?? [0, 0, 0],
    rotation: rotation ?? 0,
  }
}

/** The lens offset inside a panel-light primitive (panelLightParts), meters. */
const PANEL_LENS_LOCAL: Vec3 = [0, -0.03, 0]

/**
 * The loadmaster's task-light anchor, read off the fixture's OWN emissive part:
 * `panelLightParts` puts the lens 0.03 m below the housing centre, so the
 * socket is that primitive-local point placed through the same transform the
 * parts went through (placePoint) — the M4-T1 rig lights the real lens.
 */
function loadmasterTaskLight(): LightSocket {
  return {
    id: 'loadmaster-task-light',
    kind: 'task',
    position: placePoint(PANEL_LENS_LOCAL, placementOf('loadmaster-task-light')),
  }
}

/* -------------------------------------------------------------------- module */

/** The four lashed crate stacks, in build order (their two crates each). */
const CRATE_STACK_IDS = [
  'crate-port-aft',
  'crate-port-mid',
  'crate-stbd-aft',
  'crate-stbd-fwd',
] as const

/**
 * The authored storage module: the M1-T2 manifest entry (contract dims, the
 * standardized spine door + the contract side door, the hold's landmark
 * anchors, the derived collision hint) plus the assemblies that build it.
 */
export const STORAGE_MODULE: AuthoredModule = {
  manifest: {
    id: 'storage',
    label: 'Storage (long-haul cargo variant)',
    dimensions: [WIDTH, HEIGHT, DEPTH],
    doorSockets: [
      // The standardized spine door: −z face, flush, standard 1.0 m centre —
      // exactly the contract origin (src/validation/contractKit.ts).
      {
        id: 'spine-door',
        position: [0, STANDARD_DOOR_CENTER_M, -HALF_Z],
        facing: '-z',
      },
      // The contract's side door: +x face, standard centre, 1.0 m bow-ward.
      {
        id: 'side-door',
        position: [HALF_X, STANDARD_DOOR_CENTER_M, SIDE_DOOR_Z],
        facing: '+x',
      },
    ],
    lightSockets: [
      lightSocketOf('panel-light-aft', 'panel'),
      lightSocketOf('panel-light-mid-aft', 'panel'),
      lightSocketOf('panel-light-mid-fwd', 'panel'),
      lightSocketOf('panel-light-fwd', 'panel'),
      loadmasterTaskLight(),
      lightSocketOf('loadmaster-screen', 'screen'),
    ],
    equipmentSlots: [
      equipmentSlot('hatch-spine'),
      equipmentSlot('hatch-side'),
      ...CRATE_STACK_IDS.flatMap((id) => [
        equipmentSlot(`${id}-lower`),
        equipmentSlot(`${id}-upper`),
      ]),
      equipmentSlot('spares-rack'),
      equipmentSlot('loadmaster-bench'),
      equipmentSlot('loadmaster-screen'),
      equipmentSlot('loadmaster-task-light'),
    ],
    collisionHint: { boxes: collisionBoxesFor(STORAGE_ASSEMBLIES) },
  },
  assemblies: STORAGE_ASSEMBLIES,
}
